[package]
name = "pokeparkrando-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
parkforge = { git = "https://github.com/Mekurushi/parkforge.git", rev = "2ce703106862199b53a8bdd46b5371d3b7e2c31c" }
thiserror.workspace = true

[lints]
workspace = true
