use crate::game::global_manager::FlagName;
use crate::utils::module::ModuleName::GlobalManager;
use crate::utils::module::{lookup_module, ModuleName};

macro_rules! item {
    ($flag:ident, $module:ident, $opcode:expr $(, $param:expr )* $(,)?) => {{
        static PARAMS: &[u32] = &[$($param),*];
        (
            Itemflag::$flag,
            GiveItemDetail {
                module: ModuleName::$module,
                opcode: $opcode,
                params: PARAMS.as_ptr(),
            }
        )
    }};
}
unsafe impl Sync for GiveItemDetail {}

#[no_mangle]
static ITEM_DETAILS: &[(Itemflag, GiveItemDetail)] = &[
    item!(CHATOT_FRIENDSHIP, GlobalManager, 0x3C, 0x4),
    item!(CHIKORITA_FRIENDSHIP, GlobalManager, 0x3C, 0xB6),
    item!(TURTWIG_FRIENDSHIP, GlobalManager, 0x3C, 0x8),
    item!(TORTERRA_FRIENDSHIP, GlobalManager, 0x3C, 0x2D),
    item!(BUNEARY_FRIENDSHIP, GlobalManager, 0x3C, 0x9),
    item!(MUNCHLAX_FRIENDSHIP, GlobalManager, 0x3C, 0x13),
    item!(TREECKO_FRIENDSHIP, GlobalManager, 0x3C, 0x38),
    item!(MANKEY_FRIENDSHIP, GlobalManager, 0x3C, 0x21),
    item!(BIDOOF_FRIENDSHIP, GlobalManager, 0x3C, 0x12),
    item!(BIBAREL_FRIENDSHIP, GlobalManager, 0x3C, 0x2F),
    item!(ODDISH_FRIENDSHIP, GlobalManager, 0x3C, 0x22),
    item!(AIPOM_FRIENDSHIP, GlobalManager, 0x3C, 0xF),
    item!(AMBIPOM_FRIENDSHIP, GlobalManager, 0x3C, 0xE),
    item!(LEAFEON_FRIENDSHIP, GlobalManager, 0x3C, 0x50),
    item!(SPEAROW_FRIENDSHIP, GlobalManager, 0x3C, 0x8F),
    item!(CROAGUNK_FRIENDSHIP, GlobalManager, 0x3C, 0xB),
    item!(STARLY_FRIENDSHIP, GlobalManager, 0x3C, 0x2E),
    item!(BONSLY_FRIENDSHIP, GlobalManager, 0x3C, 0x10),
    item!(SUDOWOODO_FRIENDSHIP, GlobalManager, 0x3C, 0x6B),
    item!(PACHIRISU_FRIENDSHIP, GlobalManager, 0x3C, 0xA),
    item!(LOTAD_FRIENDSHIP, GlobalManager, 0x3C, 0x19),
    item!(SHINX_FRIENDSHIP, GlobalManager, 0x3C, 0xAE),
    item!(SCYTHER_FRIENDSHIP, GlobalManager, 0x3C, 0x45),
    item!(MAGIKARP_FRIENDSHIP, GlobalManager, 0x3C, 0x2B),
    item!(CATERPIE_FRIENDSHIP, GlobalManager, 0x3C, 0x27),
    item!(BUTTERFREE_FRIENDSHIP, GlobalManager, 0x3C, 0x8E),
    item!(WEEDLE_FRIENDSHIP, GlobalManager, 0x3C, 0x28),
    item!(SHROOMISH_FRIENDSHIP, GlobalManager, 0x3C, 0x26),
    item!(TROPIUS_FRIENDSHIP, GlobalManager, 0x3C, 0x29),
    item!(BULBASAUR_FRIENDSHIP, GlobalManager, 0x3C, 0x39),
    item!(VENUSAUR_FRIENDSHIP, GlobalManager, 0x3C, 0x68),
    item!(PIPLUP_FRIENDSHIP, GlobalManager, 0x3C, 0x6),
    item!(SLOWPOKE_FRIENDSHIP, GlobalManager, 0x3C, 0xA1),
    item!(AZURILL_FRIENDSHIP, GlobalManager, 0x3C, 0x42),
    item!(CORSOLA_FRIENDSHIP, GlobalManager, 0x3C, 0xB8),
    item!(WYNAUT_FRIENDSHIP, GlobalManager, 0x3C, 0x1D),
    item!(CARVANHA_FRIENDSHIP, GlobalManager, 0x3C, 0x7F),
    item!(SHARPEDO_FRIENDSHIP, GlobalManager, 0x3C, 0x80),
    item!(WAILORD_FRIENDSHIP, GlobalManager, 0x3C, 0x78),
    item!(TOTODILE_FRIENDSHIP, GlobalManager, 0x3C, 0xB4),
    item!(FERALIGATR_FRIENDSHIP, GlobalManager, 0x3C, 0x30),
    item!(LAPRAS_FRIENDSHIP, GlobalManager, 0x3C, 0x9E),
    item!(PSYDUCK_FRIENDSHIP, GlobalManager, 0x3C, 0xAC),
    item!(GOLDUCK_FRIENDSHIP, GlobalManager, 0x3C, 0x33),
    item!(BUIZEL_FRIENDSHIP, GlobalManager, 0x3C, 0xD),
    item!(FLOATZEL_FRIENDSHIP, GlobalManager, 0x3C, 0x7E),
    item!(VAPOREON_FRIENDSHIP, GlobalManager, 0x3C, 0x4B),
    item!(MUDKIP_FRIENDSHIP, GlobalManager, 0x3C, 0xB3),
    item!(TAILLOW_FRIENDSHIP, GlobalManager, 0x3C, 0xAD),
    item!(STARAVIA_FRIENDSHIP, GlobalManager, 0x3C, 0xC),
    item!(PIDGEOTTO_FRIENDSHIP, GlobalManager, 0x3C, 0x90),
    item!(KRABBY_FRIENDSHIP, GlobalManager, 0x3C, 0x5B),
    item!(CORPHISH_FRIENDSHIP, GlobalManager, 0x3C, 0x23),
    item!(BLASTOISE_FRIENDSHIP, GlobalManager, 0x3C, 0x2A),
    item!(WINGULL_FRIENDSHIP, GlobalManager, 0x3C, 0x59),
    item!(PELIPPER_FRIENDSHIP, GlobalManager, 0x3C, 0x5A),
    item!(GYARADOS_FRIENDSHIP, GlobalManager, 0x3C, 0x35),
    item!(GLALIE_FRIENDSHIP, GlobalManager, 0x3C, 0x82),
    item!(FROSLASS_FRIENDSHIP, GlobalManager, 0x3C, 0x51),
    item!(PILOSWINE_FRIENDSHIP, GlobalManager, 0x3C, 0x56),
    item!(MAMOSWINE_FRIENDSHIP, GlobalManager, 0x3C, 0x83),
    item!(TEDDIURSA_FRIENDSHIP, GlobalManager, 0x3C, 0xA2),
    item!(URSARING_FRIENDSHIP, GlobalManager, 0x3C, 0x86),
    item!(KIRLIA_FRIENDSHIP, GlobalManager, 0x3C, 0x7A),
    item!(SPHEAL_FRIENDSHIP, GlobalManager, 0x3C, 0x6C),
    item!(QUAGSIRE_FRIENDSHIP, GlobalManager, 0x3C, 0x69),
    item!(GLACEON_FRIENDSHIP, GlobalManager, 0x3C, 0x4C),
    item!(OCTILLERY_FRIENDSHIP, GlobalManager, 0x3C, 0xC7),
    item!(DELIBIRD_FRIENDSHIP, GlobalManager, 0x3C, 0xC6),
    item!(PRIMEAPE_FRIENDSHIP, GlobalManager, 0x3C, 0x54),
    item!(SQUIRTLE_FRIENDSHIP, GlobalManager, 0x3C, 0x2C),
    item!(SMOOCHUM_FRIENDSHIP, GlobalManager, 0x3C, 0x16),
    item!(SNEASEL_FRIENDSHIP, GlobalManager, 0x3C, 0x81),
    item!(PRINPLUP_FRIENDSHIP, GlobalManager, 0x3C, 0x6D),
    item!(EMPOLEON_FRIENDSHIP, GlobalManager, 0x3C, 0x3B),
    item!(MR_MIME_FRIENDSHIP, GlobalManager, 0x3C, 0x84),
    item!(MAWILE_FRIENDSHIP, GlobalManager, 0x3C, 0x53),
    item!(ARON_FRIENDSHIP, GlobalManager, 0x3C, 0x1F),
    item!(GIBLE_FRIENDSHIP, GlobalManager, 0x3C, 0x1C),
    item!(MAROWAK_FRIENDSHIP, GlobalManager, 0x3C, 0x70),
    item!(ZUBAT_FRIENDSHIP, GlobalManager, 0x3C, 0x5C),
    item!(GOLBAT_FRIENDSHIP, GlobalManager, 0x3C, 0x95),
    item!(DIGLETT_FRIENDSHIP, GlobalManager, 0x3C, 0x34),
    item!(DUGTRIO_FRIENDSHIP, GlobalManager, 0x3C, 0x64),
    item!(SNORLAX_FRIENDSHIP, GlobalManager, 0x3C, 0x99),
    item!(GEODUDE_FRIENDSHIP, GlobalManager, 0x3C, 0x5D),
    item!(MACHAMP_FRIENDSHIP, GlobalManager, 0x3C, 0x71),
    item!(MEOWTH_FRIENDSHIP, GlobalManager, 0x3C, 0x7D),
    item!(SCIZOR_FRIENDSHIP, GlobalManager, 0x3C, 0x47),
    item!(CRANIDOS_FRIENDSHIP, GlobalManager, 0x3C, 0x6E),
    item!(PHANPY_FRIENDSHIP, GlobalManager, 0x3C, 0x25),
    item!(RAICHU_FRIENDSHIP, GlobalManager, 0x3C, 0xA7),
    item!(MAGNEMITE_FRIENDSHIP, GlobalManager, 0x3C, 0x18),
    item!(MAGNEZONE_FRIENDSHIP, GlobalManager, 0x3C, 0x97),
    item!(HITMONLEE_FRIENDSHIP, GlobalManager, 0x3C, 0xAA),
    item!(ELECTIVIRE_FRIENDSHIP, GlobalManager, 0x3C, 0xB2),
    item!(BASTIODON_FRIENDSHIP, GlobalManager, 0x3C, 0x85),
    item!(CHARMANDER_FRIENDSHIP, GlobalManager, 0x3C, 0xB5),
    item!(HITMONTOP_FRIENDSHIP, GlobalManager, 0x3C, 0xAF),
    item!(HITMONCHAN_FRIENDSHIP, GlobalManager, 0x3C, 0xAB),
    item!(CAMERUPT_FRIENDSHIP, GlobalManager, 0x3C, 0x6F),
    item!(CHIMCHAR_FRIENDSHIP, GlobalManager, 0x3C, 0x7),
    item!(INFERNAPE_FRIENDSHIP, GlobalManager, 0x3C, 0x66),
    item!(VULPIX_FRIENDSHIP, GlobalManager, 0x3C, 0x87),
    item!(NINETALES_FRIENDSHIP, GlobalManager, 0x3C, 0x52),
    item!(FARFETCHD_FRIENDSHIP, GlobalManager, 0x3C, 0x55),
    item!(MEDITITE_FRIENDSHIP, GlobalManager, 0x3C, 0x20),
    item!(MAGBY_FRIENDSHIP, GlobalManager, 0x3C, 0x15),
    item!(MAGMORTAR_FRIENDSHIP, GlobalManager, 0x3C, 0x76),
    item!(FLAREON_FRIENDSHIP, GlobalManager, 0x3C, 0x4A),
    item!(MAGCARGO_FRIENDSHIP, GlobalManager, 0x3C, 0x58),
    item!(TORKOAL_FRIENDSHIP, GlobalManager, 0x3C, 0x57),
    item!(GOLEM_FRIENDSHIP, GlobalManager, 0x3C, 0x74),
    item!(QUILAVA_FRIENDSHIP, GlobalManager, 0x3C, 0x48),
    item!(BALTOY_FRIENDSHIP, GlobalManager, 0x3C, 0xA3),
    item!(CLAYDOL_FRIENDSHIP, GlobalManager, 0x3C, 0xA4),
    item!(PONYTA_FRIENDSHIP, GlobalManager, 0x3C, 0xB0),
    item!(RHYPERIOR_FRIENDSHIP, GlobalManager, 0x3C, 0x75),
    item!(TORCHIC_FRIENDSHIP, GlobalManager, 0x3C, 0x3F),
    item!(BLAZIKEN_FRIENDSHIP, GlobalManager, 0x3C, 0x6A),
    item!(MURKROW_FRIENDSHIP, GlobalManager, 0x3C, 0x24),
    item!(HONCHKROW_FRIENDSHIP, GlobalManager, 0x3C, 0x96),
    item!(GLISCOR_FRIENDSHIP, GlobalManager, 0x3C, 0x93),
    item!(DRIFLOON_FRIENDSHIP, GlobalManager, 0x3C, 0x61),
    item!(KAKUNA_FRIENDSHIP, GlobalManager, 0x3C, 0x31),
    item!(METAPOD_FRIENDSHIP, GlobalManager, 0x3C, 0x7B),
    item!(TANGROWTH_FRIENDSHIP, GlobalManager, 0x3C, 0xB9),
    item!(RIOLU_FRIENDSHIP, GlobalManager, 0x3C, 0x11),
    item!(SABLEYE_FRIENDSHIP, GlobalManager, 0x3C, 0x79),
    item!(SPINARAK_FRIENDSHIP, GlobalManager, 0x3C, 0x73),
    item!(BRELOOM_FRIENDSHIP, GlobalManager, 0x3C, 0x65),
    item!(PICHU_FRIENDSHIP, GlobalManager, 0x3C, 0x14),
    item!(MISDREAVUS_FRIENDSHIP, GlobalManager, 0x3C, 0x3E),
    item!(MISMAGIUS_FRIENDSHIP, GlobalManager, 0x3C, 0xA6),
    item!(ELEKID_FRIENDSHIP, GlobalManager, 0x3C, 0x17),
    item!(ELECTABUZZ_FRIENDSHIP, GlobalManager, 0x3C, 0x2),
    item!(LUXRAY_FRIENDSHIP, GlobalManager, 0x3C, 0xA8),
    item!(STUNKY_FRIENDSHIP, GlobalManager, 0x3C, 0x1E),
    item!(SKUNTANK_FRIENDSHIP, GlobalManager, 0x3C, 0x43),
    item!(VOLTORB_FRIENDSHIP, GlobalManager, 0x3C, 0x5F),
    item!(ELECTRODE_FRIENDSHIP, GlobalManager, 0x3C, 0x60),
    item!(UMBREON_FRIENDSHIP, GlobalManager, 0x3C, 0x4F),
    item!(ESPEON_FRIENDSHIP, GlobalManager, 0x3C, 0x4E),
    item!(GASTLY_FRIENDSHIP, GlobalManager, 0x3C, 0xA0),
    item!(HAUNTER_FRIENDSHIP, GlobalManager, 0x3C, 0x44),
    item!(GENGAR_FRIENDSHIP, GlobalManager, 0x3C, 0x3C),
    item!(DUSKULL_FRIENDSHIP, GlobalManager, 0x3C, 0x1A),
    item!(DUSKNOIR_FRIENDSHIP, GlobalManager, 0x3C, 0xBA),
    item!(CHARIZARD_FRIENDSHIP, GlobalManager, 0x3C, 0x3A),
    item!(FLYGON_FRIENDSHIP, GlobalManager, 0x3C, 0x9C),
    item!(PORYGON_Z_FRIENDSHIP, GlobalManager, 0x3C, 0xC8),
    item!(BRONZOR_FRIENDSHIP, GlobalManager, 0x3C, 0xA5),
    item!(TOGEKISS_FRIENDSHIP, GlobalManager, 0x3C, 0x94),
    item!(ARCANINE_FRIENDSHIP, GlobalManager, 0x3C, 0x77),
    item!(LOPUNNY_FRIENDSHIP, GlobalManager, 0x3C, 0x67),
    item!(FURRET_FRIENDSHIP, GlobalManager, 0x3C, 0x9F),
    item!(STARAPTOR_FRIENDSHIP, GlobalManager, 0x3C, 0x32),
    item!(SKORUPI_FRIENDSHIP, GlobalManager, 0x3C, 0x1B),
    item!(EEVEE_FRIENDSHIP, GlobalManager, 0x3C, 0x49),
    item!(HOPPIP_FRIENDSHIP, GlobalManager, 0x3C, 0x91),
    item!(JUMPLUFF_FRIENDSHIP, GlobalManager, 0x3C, 0x92),
    item!(AERODACTYL_FRIENDSHIP, GlobalManager, 0x3C, 0x9B),
    item!(JOLTEON_FRIENDSHIP, GlobalManager, 0x3C, 0x4D),
    item!(TYRANITAR_FRIENDSHIP, GlobalManager, 0x3C, 0xA9),
    item!(GARCHOMP_FRIENDSHIP, GlobalManager, 0x3C, 0x9A),
    item!(ABSOL_FRIENDSHIP, GlobalManager, 0x3C, 0x46),
    item!(SALAMENCE_FRIENDSHIP, GlobalManager, 0x3C, 0x9D),
    item!(BELLOSSOM_FRIENDSHIP, GlobalManager, 0x3C, 0x40),
    item!(BUDEW_FRIENDSHIP, GlobalManager, 0x3C, 0x72),
    item!(SKIPLOOM_FRIENDSHIP, GlobalManager, 0x3C, 0x41),
    item!(CYNDAQUIL_FRIENDSHIP, GlobalManager, 0x3C, 0xB7),
    item!(MAREEP_FRIENDSHIP, GlobalManager, 0x3C, 0x3D),
    item!(DRAGONITE_FRIENDSHIP, GlobalManager, 0x3C, 0x98),
    item!(LUCARIO_FRIENDSHIP, GlobalManager, 0x3C, 0x3),
    item!(RAYQUAZA_FRIENDSHIP, GlobalManager, 0x3C, 0x63),
    item!(DRIFBLIM_FRIENDSHIP, GlobalManager, 0x3C, 0x62),
    item!(BURMY_FRIENDSHIP, GlobalManager, 0x3C, 0x7C),
    item!(MIME_JR_FRIENDSHIP, GlobalManager, 0x3C, 0x1),
    item!(ABRA_FRIENDSHIP, GlobalManager, 0x3C, 0x5E),
    item!(MEW_FRIENDSHIP, GlobalManager, 0x3C, 0x5),
    item!(JIRACHI_FRIENDSHIP, GlobalManager, 0x3C, 0xC0),
    item!(MANAPHY_FRIENDSHIP, GlobalManager, 0x3C, 0xC2),
    item!(LATIAS_FRIENDSHIP, GlobalManager, 0x3C, 0xBC),
    item!(SUICUNE_FRIENDSHIP, GlobalManager, 0x3C, 0xC4),
    item!(METAGROSS_FRIENDSHIP, GlobalManager, 0x3C, 0xB1),
    item!(HEATRAN_FRIENDSHIP, GlobalManager, 0x3C, 0xC1),
    item!(GROUDON_FRIENDSHIP, GlobalManager, 0x3C, 0xBF),
    item!(CELEBI_FRIENDSHIP, GlobalManager, 0x3C, 0xBB),
    item!(DARKRAI_FRIENDSHIP, GlobalManager, 0x3C, 0xC3),
    item!(ROTOM_FRIENDSHIP, GlobalManager, 0x3C, 0x88),
    item!(SHAYMIN_FRIENDSHIP, GlobalManager, 0x3C, 0x36),
    item!(LATIOS_FRIENDSHIP, GlobalManager, 0x3C, 0xBD),
    item!(DEOXYS_FRIENDSHIP, GlobalManager, 0x3C, 0xC5),
    item!(TROPIUS_UNLOCK, GlobalManager, 0x28, 0x17),
    item!(PACHIRISU_UNLOCK, GlobalManager, 0x28, 0x4),
    item!(BONSLY_UNLOCK, GlobalManager, 0x28, 0xF),
    item!(SUDOWOODO_UNLOCK, GlobalManager, 0x28, 0x57),
    item!(LOTAD_UNLOCK, GlobalManager, 0x28, 0x9),
    item!(SHINX_UNLOCK, GlobalManager, 0x28, 0x10),
    item!(SCYTHER_UNLOCK, GlobalManager, 0x28, 0x1B),
    item!(CATERPIE_UNLOCK, GlobalManager, 0x28, 0xA),
    item!(BUTTERFREE_UNLOCK, GlobalManager, 0x28, 0x16),
    item!(CHIMCHAR_UNLOCK, GlobalManager, 0x28, 0x7),
    item!(AMBIPOM_UNLOCK, GlobalManager, 0x28, 0x19),
    item!(WEEDLE_UNLOCK, GlobalManager, 0x28, 0xB),
    item!(SHROOMISH_UNLOCK, GlobalManager, 0x28, 0xE),
    item!(MAGIKARP_UNLOCK, GlobalManager, 0x28, 0x8),
    item!(BIDOOF_UNLOCK, GlobalManager, 0x28, 0x20),
    item!(BIDOOF_2_UNLOCK, GlobalManager, 0x28, 0x21),
    item!(BIDOOF_3_UNLOCK, GlobalManager, 0x28, 0x22),
    item!(BEACH_BIDOOF_UNLOCK, GlobalManager, 0x28, 0x9C),
    item!(BIBAREL_UNLOCK, GlobalManager, 0x28, 0x18),
    item!(STARLY_UNLOCK, GlobalManager, 0x28, 0x15),
    item!(STARLY_2_UNLOCK, GlobalManager, 0x28, 0x25),
    item!(TORTERRA_UNLOCK, GlobalManager, 0x28, 0x14),
    item!(FLOATZEL_UNLOCK, GlobalManager, 0x28, 0x3A),
    item!(MUDKIP_UNLOCK, GlobalManager, 0x28, 0x33),
    item!(TOTODILE_UNLOCK, GlobalManager, 0x28, 0x32),
    item!(GOLDUCK_UNLOCK, GlobalManager, 0x28, 0x39),
    item!(KRABBY_UNLOCK, GlobalManager, 0x28, 0x31),
    item!(CORPHISH_UNLOCK, GlobalManager, 0x28, 0x34),
    item!(DELIBIRD_UNLOCK, GlobalManager, 0x28, 0x4A),
    item!(SQUIRTLE_UNLOCK, GlobalManager, 0x28, 0x4C),
    item!(SMOOCHUM_UNLOCK, GlobalManager, 0x28, 0x4B),
    item!(SNEASEL_UNLOCK, GlobalManager, 0x28, 0x48),
    item!(MAMOSWINE_UNLOCK, GlobalManager, 0x28, 0x53),
    item!(GLALIE_UNLOCK, GlobalManager, 0x28, 0xB8),
    item!(PRIMEAPE_UNLOCK, GlobalManager, 0x28, 0x4E),
    item!(URSARING_UNLOCK, GlobalManager, 0x28, 0x4F),
    item!(MAGNEMITE_UNLOCK, GlobalManager, 0x28, 0x58),
    item!(MACHAMP_UNLOCK, GlobalManager, 0x28, 0x99),
    item!(MAGNEMITE_2_UNLOCK, GlobalManager, 0x28, 0xA8),
    item!(MAGNEMITE_3_UNLOCK, GlobalManager, 0x28, 0xA9),
    item!(DIGLETT_UNLOCK, GlobalManager, 0x28, 0x9A),
    item!(MAGNEZONE_UNLOCK, GlobalManager, 0x28, 0x67),
    item!(PHANPY_UNLOCK, GlobalManager, 0x28, 0x59),
    item!(RAICHU_UNLOCK, GlobalManager, 0x28, 0x5F),
    item!(INFERNAPE_UNLOCK, GlobalManager, 0x28, 0x6B),
    item!(NINETALES_UNLOCK, GlobalManager, 0x28, 0x75),
    item!(PONYTA_UNLOCK, GlobalManager, 0x28, 0x1A),
    item!(TORKOAL_UNLOCK, GlobalManager, 0x28, 0x63),
    item!(GOLEM_UNLOCK, GlobalManager, 0x28, 0x6C),
    item!(BALTOY_UNLOCK, GlobalManager, 0x28, 0x9D),
    item!(CLAYDOL_UNLOCK, GlobalManager, 0x28, 0x65),
    item!(HITMONCHAN_UNLOCK, GlobalManager, 0x28, 0x69),
    item!(HITMONLEE_UNLOCK, GlobalManager, 0x28, 0x60),
    item!(HONCHKROW_UNLOCK, GlobalManager, 0x28, 0xA0),
    item!(METAPOD_UNLOCK, GlobalManager, 0x28, 0x72),
    item!(KAKUNA_UNLOCK, GlobalManager, 0x28, 0x71),
    item!(VOLTORB_UNLOCK, GlobalManager, 0x28, 0xB7),
    item!(ELEKID_UNLOCK, GlobalManager, 0x28, 0xAD),
    item!(ELECTABUZZ_UNLOCK, GlobalManager, 0x28, 0x66),
    item!(LUXRAY_UNLOCK, GlobalManager, 0x28, 0x81),
    item!(STUNKY_UNLOCK, GlobalManager, 0x28, 0xA1),
    item!(SKUNTANK_UNLOCK, GlobalManager, 0x28, 0x7F),
    item!(BRELOOM_UNLOCK, GlobalManager, 0x28, 0x74),
    item!(MISMAGIUS_UNLOCK, GlobalManager, 0x28, 0x80),
    item!(ELECTRODE_UNLOCK, GlobalManager, 0x28, 0xA3),
    item!(HAUNTER_UNLOCK, GlobalManager, 0x28, 0x7D),
    item!(GASTLY_UNLOCK, GlobalManager, 0x28, 0xA2),
    item!(GASTLY_2_UNLOCK, GlobalManager, 0x28, 0xA7),
    item!(DUSKNOIR_UNLOCK, GlobalManager, 0x28, 0x84),
    item!(ESPEON_UNLOCK, GlobalManager, 0x28, 0x82),
    item!(GENGAR_UNLOCK, GlobalManager, 0x28, 0x83),
    item!(BLASTOISE_UNLOCK, GlobalManager, 0x28, 0x3D),
    item!(ELECTIVIRE_UNLOCK, GlobalManager, 0x28, 0x61),
    item!(MAGMORTAR_UNLOCK, GlobalManager, 0x28, 0x9E),
    item!(JOLTEON_UNLOCK, GlobalManager, 0x28, 0x8D),
    item!(AERODACTYL_UNLOCK, GlobalManager, 0x28, 0xB4),
    item!(TYRANITAR_UNLOCK, GlobalManager, 0x28, 0x86),
    item!(GARCHOMP_UNLOCK, GlobalManager, 0x28, 0x85),
    item!(RAYQUAZA_UNLOCK, GlobalManager, 0x28, 0x95),
    item!(CELEBI_UNLOCK, GlobalManager, 0x28, 0xA5),
    item!(DARKRAI_UNLOCK, GlobalManager, 0x28, 0xA4),
    item!(GROUDON_UNLOCK, GlobalManager, 0x28, 0x9F),
    item!(JIRACHI_UNLOCK, GlobalManager, 0x28, 0xA6),
    item!(PIKACHU_BALLOON, GlobalManager, 0xB7, 0x3),
    item!(PIKACHU_SURFBOARD, GlobalManager, 0xB7, 0x0),
    item!(PIKACHU_SNOWBOARD, GlobalManager, 0xB7, 0x2),
    item!(BERRIES_10, GlobalManager, 0xA, 0xA),
    item!(BERRIES_20, GlobalManager, 0xA, 0x14),
    item!(BERRIES_50, GlobalManager, 0xA, 0x32),
    item!(BERRIES_100, GlobalManager, 0xA, 0x64),
    item!(BULBASAUR_PRISMA, GlobalManager, 0x52, 0xF),
    item!(VENUSAUR_PRISMA, GlobalManager, 0x52, 0x2),
    item!(PELIPPER_PRISMA, GlobalManager, 0x52, 0x6),
    item!(GYARADOS_PRISMA, GlobalManager, 0x52, 0x5),
    item!(EMPOLEON_PRISMA, GlobalManager, 0x52, 0x8),
    item!(BASTIODON_PRISMA, GlobalManager, 0x52, 0x9),
    item!(RHYPERIOR_PRISMA, GlobalManager, 0x52, 0xA),
    item!(BLAZIKEN_PRISMA, GlobalManager, 0x52, 0xB),
    item!(TANGROWTH_PRISMA, GlobalManager, 0x52, 0x3),
    item!(DUSKNOIR_PRISMA, GlobalManager, 0x52, 0x4),
    item!(ROTOM_PRISMA, GlobalManager, 0x52, 0xC),
    item!(ABSOL_PRISMA, GlobalManager, 0x52, 0x0),
    item!(SALAMENCE_PRISMA, GlobalManager, 0x52, 0xE),
    item!(RAYQUAZA_PRISMA, GlobalManager, 0x52, 0x1),
    item!(PROGRESSIVE_DASH, GlobalManager, 0xB9, 0x1, 0x1),
    item!(PROGRESSIVE_THUNDERBOLT, GlobalManager, 0xB9, 0x10, 0x1),
    item!(PROGRESSIVE_HEALTH, GlobalManager, 0xB9, 0x100, 0x1),
    item!(PROGRESSIVE_IRON_TAIL, GlobalManager, 0xB9, 0x800, 0x1),
    item!(DOUBLE_DASH, GlobalManager, 0xB9, 0x2, 0x1),
    item!(
        MEADOW_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0101FuwarideTaxiStop as u32
    ),
    item!(
        BEACH_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0301FuwarideTaxiStop as u32
    ),
    item!(
        ICE_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0302FuwarideTaxiStop as u32
    ),
    item!(
        CAVERN_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0401FuwarideTaxiStop as u32
    ),
    item!(
        MAGMA_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0402FuwarideTaxiStop as u32
    ),
    item!(
        HAUNTED_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0501FuwarideTaxiStop as u32
    ),
    item!(
        GRANITE_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0601FuwarideTaxiStop as u32
    ),
    item!(
        FLOWER_ZONE_FAST_TRAVEL,
        GlobalManager,
        0x0,
        FlagName::F0602FuwarideTaxiStop as u32
    ),
    item!(
        BEACH_BRIDGE_1_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::FMap0301Bridge1Build as u32
    ),
    item!(
        BEACH_BRIDGE_2_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::FMap0301Bridge3Build as u32
    ),
    item!(
        MAGMA_ZONE_FIRE_WALL_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::F0402FireWallA as u32
    ),
    item!(
        HAUNTED_ZONE_MANSION_GEM_DOORS_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::F0502DoorA as u32
    ),
    item!(
        ICE_ZONE_FROZEN_LAKE_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::FPondFreeze as u32
    ),
    item!(
        ICE_ZONE_LIFT_UNLOCK,
        GlobalManager,
        0x0,
        FlagName::F0302Lift as u32
    ),
];

#[no_mangle]
pub fn get_item_detail(flag: u16) -> Option<&'static GiveItemDetail> {
    ITEM_DETAILS
        .iter()
        .find(|(f, _)| *f as u16 == flag)
        .map(|(_, d)| d)
}

#[repr(C)]
pub struct GiveItemDetail {
    pub module: ModuleName,
    pub opcode: u32,
    pub params: *const u32,
}

#[derive(Copy, Clone, Hash, PartialEq, Eq)]
#[allow(non_camel_case_types)]
#[repr(u16)]
pub enum Itemflag {
    // Friendship Items
    CHATOT_FRIENDSHIP           = 0,
    CHIKORITA_FRIENDSHIP        = 1,
    TURTWIG_FRIENDSHIP          = 2,
    TORTERRA_FRIENDSHIP         = 3,
    BUNEARY_FRIENDSHIP          = 4,
    MUNCHLAX_FRIENDSHIP         = 5,
    TREECKO_FRIENDSHIP          = 6,
    MANKEY_FRIENDSHIP           = 7,
    BIDOOF_FRIENDSHIP           = 8,
    BIBAREL_FRIENDSHIP          = 9,
    ODDISH_FRIENDSHIP           = 10,
    AIPOM_FRIENDSHIP            = 11,
    AMBIPOM_FRIENDSHIP          = 12,
    LEAFEON_FRIENDSHIP          = 13,
    SPEAROW_FRIENDSHIP          = 14,
    CROAGUNK_FRIENDSHIP         = 15,
    STARLY_FRIENDSHIP           = 16,
    BONSLY_FRIENDSHIP           = 17,
    SUDOWOODO_FRIENDSHIP        = 18,
    PACHIRISU_FRIENDSHIP        = 19,
    LOTAD_FRIENDSHIP            = 20,
    SHINX_FRIENDSHIP            = 21,
    SCYTHER_FRIENDSHIP          = 22,
    MAGIKARP_FRIENDSHIP         = 23,
    CATERPIE_FRIENDSHIP         = 24,
    BUTTERFREE_FRIENDSHIP       = 25,
    WEEDLE_FRIENDSHIP           = 26,
    SHROOMISH_FRIENDSHIP        = 27,
    TROPIUS_FRIENDSHIP          = 28,
    BULBASAUR_FRIENDSHIP        = 29,
    VENUSAUR_FRIENDSHIP         = 30,
    PIPLUP_FRIENDSHIP           = 31,
    SLOWPOKE_FRIENDSHIP         = 32,
    AZURILL_FRIENDSHIP          = 33,
    CORSOLA_FRIENDSHIP          = 34,
    WYNAUT_FRIENDSHIP           = 35,
    CARVANHA_FRIENDSHIP         = 36,
    SHARPEDO_FRIENDSHIP         = 37,
    WAILORD_FRIENDSHIP          = 38,
    TOTODILE_FRIENDSHIP         = 39,
    FERALIGATR_FRIENDSHIP       = 40,
    LAPRAS_FRIENDSHIP           = 41,
    PSYDUCK_FRIENDSHIP          = 42,
    GOLDUCK_FRIENDSHIP          = 43,
    BUIZEL_FRIENDSHIP           = 44,
    FLOATZEL_FRIENDSHIP         = 45,
    VAPOREON_FRIENDSHIP         = 46,
    MUDKIP_FRIENDSHIP           = 47,
    TAILLOW_FRIENDSHIP          = 48,
    STARAVIA_FRIENDSHIP         = 49,
    PIDGEOTTO_FRIENDSHIP        = 50,
    KRABBY_FRIENDSHIP           = 51,
    CORPHISH_FRIENDSHIP         = 52,
    BLASTOISE_FRIENDSHIP        = 53,
    WINGULL_FRIENDSHIP          = 54,
    PELIPPER_FRIENDSHIP         = 55,
    GYARADOS_FRIENDSHIP         = 56,
    GLALIE_FRIENDSHIP           = 57,
    FROSLASS_FRIENDSHIP         = 58,
    PILOSWINE_FRIENDSHIP        = 59,
    MAMOSWINE_FRIENDSHIP        = 60,
    TEDDIURSA_FRIENDSHIP        = 61,
    URSARING_FRIENDSHIP         = 62,
    KIRLIA_FRIENDSHIP           = 63,
    SPHEAL_FRIENDSHIP           = 64,
    QUAGSIRE_FRIENDSHIP         = 65,
    GLACEON_FRIENDSHIP          = 66,
    OCTILLERY_FRIENDSHIP        = 67,
    DELIBIRD_FRIENDSHIP         = 68,
    PRIMEAPE_FRIENDSHIP         = 69,
    SQUIRTLE_FRIENDSHIP         = 70,
    SMOOCHUM_FRIENDSHIP         = 71,
    SNEASEL_FRIENDSHIP          = 72,
    PRINPLUP_FRIENDSHIP         = 73,
    EMPOLEON_FRIENDSHIP         = 74,
    MR_MIME_FRIENDSHIP          = 75,
    MAWILE_FRIENDSHIP           = 76,
    ARON_FRIENDSHIP             = 77,
    GIBLE_FRIENDSHIP            = 78,
    MAROWAK_FRIENDSHIP          = 79,
    ZUBAT_FRIENDSHIP            = 80,
    GOLBAT_FRIENDSHIP           = 81,
    DIGLETT_FRIENDSHIP          = 82,
    DUGTRIO_FRIENDSHIP          = 83,
    SNORLAX_FRIENDSHIP          = 84,
    GEODUDE_FRIENDSHIP          = 85,
    MACHAMP_FRIENDSHIP          = 86,
    MEOWTH_FRIENDSHIP           = 87,
    SCIZOR_FRIENDSHIP           = 88,
    CRANIDOS_FRIENDSHIP         = 89,
    PHANPY_FRIENDSHIP           = 90,
    RAICHU_FRIENDSHIP           = 91,
    MAGNEMITE_FRIENDSHIP        = 92,
    MAGNEZONE_FRIENDSHIP        = 93,
    HITMONLEE_FRIENDSHIP        = 94,
    ELECTIVIRE_FRIENDSHIP       = 95,
    BASTIODON_FRIENDSHIP        = 96,
    CHARMANDER_FRIENDSHIP       = 97,
    HITMONTOP_FRIENDSHIP        = 98,
    HITMONCHAN_FRIENDSHIP       = 99,
    CAMERUPT_FRIENDSHIP         = 100,
    CHIMCHAR_FRIENDSHIP         = 101,
    INFERNAPE_FRIENDSHIP        = 102,
    VULPIX_FRIENDSHIP           = 103,
    NINETALES_FRIENDSHIP        = 104,
    FARFETCHD_FRIENDSHIP        = 105,
    MEDITITE_FRIENDSHIP         = 106,
    MAGBY_FRIENDSHIP            = 107,
    MAGMORTAR_FRIENDSHIP        = 108,
    FLAREON_FRIENDSHIP          = 109,
    MAGCARGO_FRIENDSHIP         = 110,
    TORKOAL_FRIENDSHIP          = 111,
    GOLEM_FRIENDSHIP            = 112,
    QUILAVA_FRIENDSHIP          = 113,
    BALTOY_FRIENDSHIP           = 114,
    CLAYDOL_FRIENDSHIP          = 115,
    PONYTA_FRIENDSHIP           = 116,
    RHYPERIOR_FRIENDSHIP        = 117,
    TORCHIC_FRIENDSHIP          = 118,
    BLAZIKEN_FRIENDSHIP         = 119,
    MURKROW_FRIENDSHIP          = 120,
    HONCHKROW_FRIENDSHIP        = 121,
    GLISCOR_FRIENDSHIP          = 122,
    DRIFLOON_FRIENDSHIP         = 123,
    KAKUNA_FRIENDSHIP           = 124,
    METAPOD_FRIENDSHIP          = 125,
    TANGROWTH_FRIENDSHIP        = 126,
    RIOLU_FRIENDSHIP            = 127,
    SABLEYE_FRIENDSHIP          = 128,
    SPINARAK_FRIENDSHIP         = 129,
    BRELOOM_FRIENDSHIP          = 130,
    PICHU_FRIENDSHIP            = 131,
    MISDREAVUS_FRIENDSHIP       = 132,
    MISMAGIUS_FRIENDSHIP        = 133,
    ELEKID_FRIENDSHIP           = 134,
    ELECTABUZZ_FRIENDSHIP       = 135,
    LUXRAY_FRIENDSHIP           = 136,
    STUNKY_FRIENDSHIP           = 137,
    SKUNTANK_FRIENDSHIP         = 138,
    VOLTORB_FRIENDSHIP          = 139,
    ELECTRODE_FRIENDSHIP        = 140,
    UMBREON_FRIENDSHIP          = 141,
    ESPEON_FRIENDSHIP           = 142,
    GASTLY_FRIENDSHIP           = 143,
    HAUNTER_FRIENDSHIP          = 144,
    GENGAR_FRIENDSHIP           = 145,
    DUSKULL_FRIENDSHIP          = 146,
    DUSKNOIR_FRIENDSHIP         = 147,
    CHARIZARD_FRIENDSHIP        = 148,
    FLYGON_FRIENDSHIP           = 149,
    PORYGON_Z_FRIENDSHIP        = 150,
    BRONZOR_FRIENDSHIP          = 151,
    TOGEKISS_FRIENDSHIP         = 152,
    ARCANINE_FRIENDSHIP         = 153,
    LOPUNNY_FRIENDSHIP          = 154,
    FURRET_FRIENDSHIP           = 155,
    STARAPTOR_FRIENDSHIP        = 156,
    SKORUPI_FRIENDSHIP          = 157,
    EEVEE_FRIENDSHIP            = 158,
    HOPPIP_FRIENDSHIP           = 159,
    JUMPLUFF_FRIENDSHIP         = 160,
    AERODACTYL_FRIENDSHIP       = 161,
    JOLTEON_FRIENDSHIP          = 162,
    TYRANITAR_FRIENDSHIP        = 163,
    GARCHOMP_FRIENDSHIP         = 164,
    ABSOL_FRIENDSHIP            = 165,
    SALAMENCE_FRIENDSHIP        = 166,
    BELLOSSOM_FRIENDSHIP        = 167,
    BUDEW_FRIENDSHIP            = 168,
    SKIPLOOM_FRIENDSHIP         = 169,
    CYNDAQUIL_FRIENDSHIP        = 170,
    MAREEP_FRIENDSHIP           = 171,
    DRAGONITE_FRIENDSHIP        = 172,
    LUCARIO_FRIENDSHIP          = 173,
    RAYQUAZA_FRIENDSHIP         = 174,
    DRIFBLIM_FRIENDSHIP         = 175,
    BURMY_FRIENDSHIP            = 176,
    MIME_JR_FRIENDSHIP          = 177,
    ABRA_FRIENDSHIP             = 178,
    MEW_FRIENDSHIP              = 179,
    JIRACHI_FRIENDSHIP          = 180,
    MANAPHY_FRIENDSHIP          = 181,
    LATIAS_FRIENDSHIP           = 182,
    SUICUNE_FRIENDSHIP          = 183,
    METAGROSS_FRIENDSHIP        = 184,
    HEATRAN_FRIENDSHIP          = 185,
    GROUDON_FRIENDSHIP          = 186,
    CELEBI_FRIENDSHIP           = 187,
    DARKRAI_FRIENDSHIP          = 188,
    ROTOM_FRIENDSHIP            = 189,
    SHAYMIN_FRIENDSHIP          = 190,
    LATIOS_FRIENDSHIP           = 191,
    DEOXYS_FRIENDSHIP           = 192,

    // Unlock Items
    TROPIUS_UNLOCK              = 193,
    PACHIRISU_UNLOCK            = 194,
    BONSLY_UNLOCK               = 195,
    SUDOWOODO_UNLOCK            = 196,
    LOTAD_UNLOCK                = 197,
    SHINX_UNLOCK                = 198,
    SCYTHER_UNLOCK              = 199,
    CATERPIE_UNLOCK             = 200,
    BUTTERFREE_UNLOCK           = 201,
    CHIMCHAR_UNLOCK             = 202,
    AMBIPOM_UNLOCK              = 203,
    WEEDLE_UNLOCK               = 204,
    SHROOMISH_UNLOCK            = 205,
    MAGIKARP_UNLOCK             = 206,
    BIDOOF_UNLOCK               = 207,
    BIDOOF_2_UNLOCK             = 208,
    BIDOOF_3_UNLOCK             = 209,
    BEACH_BIDOOF_UNLOCK         = 210,
    BIBAREL_UNLOCK              = 211,
    STARLY_UNLOCK               = 212,
    STARLY_2_UNLOCK             = 213,
    TORTERRA_UNLOCK             = 214,
    FLOATZEL_UNLOCK             = 215,
    MUDKIP_UNLOCK               = 216,
    TOTODILE_UNLOCK             = 217,
    GOLDUCK_UNLOCK              = 218,
    KRABBY_UNLOCK               = 219,
    CORPHISH_UNLOCK             = 220,
    DELIBIRD_UNLOCK             = 221,
    SQUIRTLE_UNLOCK             = 222,
    SMOOCHUM_UNLOCK             = 223,
    SNEASEL_UNLOCK              = 224,
    MAMOSWINE_UNLOCK            = 225,
    GLALIE_UNLOCK               = 226,
    PRIMEAPE_UNLOCK             = 227,
    URSARING_UNLOCK             = 228,
    MAGNEMITE_UNLOCK            = 229,
    MACHAMP_UNLOCK              = 230,
    MAGNEMITE_2_UNLOCK          = 231,
    MAGNEMITE_3_UNLOCK          = 232,
    DIGLETT_UNLOCK              = 233,
    MAGNEZONE_UNLOCK            = 234,
    PHANPY_UNLOCK               = 235,
    RAICHU_UNLOCK               = 236,
    INFERNAPE_UNLOCK            = 237,
    NINETALES_UNLOCK            = 238,
    PONYTA_UNLOCK               = 239,
    TORKOAL_UNLOCK              = 240,
    GOLEM_UNLOCK                = 241,
    BALTOY_UNLOCK               = 242,
    CLAYDOL_UNLOCK              = 243,
    HITMONCHAN_UNLOCK           = 244,
    HITMONLEE_UNLOCK            = 245,
    HONCHKROW_UNLOCK            = 246,
    METAPOD_UNLOCK              = 247,
    KAKUNA_UNLOCK               = 248,
    VOLTORB_UNLOCK              = 249,
    ELEKID_UNLOCK               = 250,
    ELECTABUZZ_UNLOCK           = 251,
    LUXRAY_UNLOCK               = 252,
    STUNKY_UNLOCK               = 253,
    SKUNTANK_UNLOCK             = 254,
    BRELOOM_UNLOCK              = 255,
    MISMAGIUS_UNLOCK            = 256,
    ELECTRODE_UNLOCK            = 257,
    HAUNTER_UNLOCK              = 258,
    GASTLY_UNLOCK               = 259,
    GASTLY_2_UNLOCK             = 260,
    DUSKNOIR_UNLOCK             = 261,
    ESPEON_UNLOCK               = 262,
    GENGAR_UNLOCK               = 263,
    BLASTOISE_UNLOCK            = 264,
    ELECTIVIRE_UNLOCK           = 265,
    MAGMORTAR_UNLOCK            = 266,
    JOLTEON_UNLOCK              = 267,
    AERODACTYL_UNLOCK           = 268,
    TYRANITAR_UNLOCK            = 269,
    GARCHOMP_UNLOCK             = 270,
    RAYQUAZA_UNLOCK             = 271,
    CELEBI_UNLOCK               = 272,
    DARKRAI_UNLOCK              = 273,
    GROUDON_UNLOCK              = 274,
    JIRACHI_UNLOCK              = 275,

    // Password Items
    PIKACHU_BALLOON             = 276,
    PIKACHU_SURFBOARD           = 277,
    PIKACHU_SNOWBOARD           = 278,

    // Berry Items
    BERRIES_10                  = 279,
    BERRIES_20                  = 280,
    BERRIES_50                  = 281,
    BERRIES_100                 = 282,

    // Prisma Items
    BULBASAUR_PRISMA            = 283,
    VENUSAUR_PRISMA             = 284,
    PELIPPER_PRISMA             = 285,
    GYARADOS_PRISMA             = 286,
    EMPOLEON_PRISMA             = 287,
    BASTIODON_PRISMA            = 288,
    RHYPERIOR_PRISMA            = 289,
    BLAZIKEN_PRISMA             = 290,
    TANGROWTH_PRISMA            = 291,
    DUSKNOIR_PRISMA             = 292,
    ROTOM_PRISMA                = 293,
    ABSOL_PRISMA                = 294,
    SALAMENCE_PRISMA            = 295,
    RAYQUAZA_PRISMA             = 296,

    PROGRESSIVE_DASH            = 297,
    PROGRESSIVE_THUNDERBOLT     = 298,
    PROGRESSIVE_HEALTH          = 299,
    PROGRESSIVE_IRON_TAIL       = 300,

    DOUBLE_DASH                 = 301,

    // Fast Travel Flag Items
    MEADOW_ZONE_FAST_TRAVEL     = 302,
    BEACH_ZONE_FAST_TRAVEL      = 303,
    ICE_ZONE_FAST_TRAVEL        = 304,
    CAVERN_ZONE_FAST_TRAVEL     = 305,
    MAGMA_ZONE_FAST_TRAVEL      = 306,
    HAUNTED_ZONE_FAST_TRAVEL    = 307,
    GRANITE_ZONE_FAST_TRAVEL    = 308,
    FLOWER_ZONE_FAST_TRAVEL     = 309,

    // Unlock Flag Items
    BEACH_BRIDGE_1_UNLOCK       = 310,
    BEACH_BRIDGE_2_UNLOCK       = 311,
    MAGMA_ZONE_FIRE_WALL_UNLOCK = 312,
    HAUNTED_ZONE_MANSION_GEM_DOORS_UNLOCK = 313,
    ICE_ZONE_FROZEN_LAKE_UNLOCK = 314,
    ICE_ZONE_LIFT_UNLOCK        = 315,
}

// TODO: define Power Params cleanly; maybe even smarter helper function
pub fn get_dash_params() -> *const u32 {
    let module = unsafe { lookup_module(&GlobalManager.as_ptr()) };
    let vtable = unsafe { (*module).vtable };
    let syscall_handler = unsafe { (*vtable).syscall_handler };
    let call = |arg: u32| unsafe { syscall_handler(module, 0xBA, [arg].as_ptr()) };

    if !call(0x1) {
        return [0x1, 0x1].as_ptr();
    }
    if !call(0x4) {
        return [0x4, 0x1].as_ptr();
    }
    if !call(0x8) {
        return [0x8, 0x1].as_ptr();
    }
    [0x4000, 0x1].as_ptr()
}

pub fn get_thunderbolt_params() -> *const u32 {
    let module = unsafe { lookup_module(&GlobalManager.as_ptr()) };
    let vtable = unsafe { (*module).vtable };
    let syscall_handler = unsafe { (*vtable).syscall_handler };
    let call = |arg: u32| unsafe { syscall_handler(module, 0xBA, [arg].as_ptr()) };

    if !call(0x10) {
        return [0x10, 0x1].as_ptr();
    }
    if !call(0x20) {
        return [0x20, 0x1].as_ptr();
    }
    if !call(0x40) {
        return [0x40, 0x1].as_ptr();
    }
    [0x80, 0x1].as_ptr()
}

pub fn get_health_params() -> *const u32 {
    let module = unsafe { lookup_module(&GlobalManager.as_ptr()) };
    let vtable = unsafe { (*module).vtable };
    let syscall_handler = unsafe { (*vtable).syscall_handler };
    let call = |arg: u32| unsafe { syscall_handler(module, 0xBA, [arg].as_ptr()) };

    if !call(0x100) {
        return [0x100, 0x1].as_ptr();
    }
    if !call(0x200) {
        return [0x200, 0x1].as_ptr();
    }
    [0x400, 0x1].as_ptr()
}

pub fn get_iron_tail_params() -> *const u32 {
    let module = unsafe { lookup_module(&GlobalManager.as_ptr()) };
    let vtable = unsafe { (*module).vtable };
    let syscall_handler = unsafe { (*vtable).syscall_handler };
    let call = |arg: u32| unsafe { syscall_handler(module, 0xBA, [arg].as_ptr()) };

    if !call(0x800) {
        return [0x800, 0x1].as_ptr();
    }
    if !call(0x1000) {
        return [0x1000, 0x1].as_ptr();
    }
    [0x2000, 0x1].as_ptr()
}
