"""
AUTO-GENERATED FILE — DO NOT EDIT
"""

ABSOL_S_HURDLE_BOUNCE_ATTRACTION_ATTRACTION_MENU = "Absol's Hurdle Bounce Attraction - Attraction Menu"
BASTIODON_S_PANEL_CRUSH_ATTRACTION_ATTRACTION_MENU = "Bastiodon's Panel Crush Attraction - Attraction Menu"
BEACH_CORPHISH_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Beach Corphish - Battle Power Competition -- Friendship'
BEACH_KRABBY_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Beach Krabby - Chase Power Competition -- Friendship'
BEACH_MUDKIP_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Beach Mudkip - Hide and Seek Power Competition -- Friendship'
BEACH_SPEAROW_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Beach Spearow - Battle Power Competition -- Friendship'
BEACH_STARAVIA_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Beach Staravia - Battle Power Competition -- Friendship'
BEACH_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Beach Starly - Chase Power Competition -- Friendship'
BEACH_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Beach Taillow - Chase Power Competition -- Friendship'
BEACH_WINGULL_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Beach Wingull - Chase Power Competition -- Friendship'
BEACH_ZONE_LAPRAS_AREA_BEACH_ZONE_LAPRAS = 'Beach Zone Lapras Area - Beach Zone Lapras'
BEACH_ZONE_LAPRAS_AREA_MAIN_AREA_ROCK = 'Beach Zone Lapras Area - Main Area Rock'
BEACH_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Cavern Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_CORPHISH = 'Beach Zone Main Area - Corphish'
BEACH_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Flower Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Granite Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Haunted Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Ice Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_KRABBY = 'Beach Zone Main Area - Krabby'
BEACH_ZONE_MAIN_AREA_LAPRAS_AREA_ROCK = 'Beach Zone Main Area - Lapras Area Rock'
BEACH_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Magma Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Meadow Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_MIDDLE_BRIDGE = 'Beach Zone Main Area - Middle Bridge'
BEACH_ZONE_MAIN_AREA_MUDKIP = 'Beach Zone Main Area - Mudkip'
BEACH_ZONE_MAIN_AREA_PELIPPER_ATTRACTION = 'Beach Zone Main Area - Pelipper Attraction'
BEACH_ZONE_MAIN_AREA_RECYCLE_BRIDGE = 'Beach Zone Main Area - Recycle Bridge'
BEACH_ZONE_MAIN_AREA_SPEAROW = 'Beach Zone Main Area - Spearow'
BEACH_ZONE_MAIN_AREA_STARAVIA = 'Beach Zone Main Area - Staravia'
BEACH_ZONE_MAIN_AREA_STARLY = 'Beach Zone Main Area - Starly'
BEACH_ZONE_MAIN_AREA_TAILLOW = 'Beach Zone Main Area - Taillow'
BEACH_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION = 'Beach Zone Main Area - Treehouse Connection'
BEACH_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Beach Zone Main Area - Treehouse Drifblim Fast Travel'
BEACH_ZONE_MAIN_AREA_WINGULL = 'Beach Zone Main Area - Wingull'
BEACH_ZONE_MIDDLE_ISLE_MAIN_BRIDGE = 'Beach Zone Middle Isle - Main Bridge'
BEACH_ZONE_RECYCLE_AREA_GYARADOS_ATTRACTION = 'Beach Zone Recycle Area - Gyarados Attraction'
BEACH_ZONE_RECYCLE_AREA_MAIN_BRIDGE = 'Beach Zone Recycle Area - Main Bridge'
BLAZIKEN_S_BOULDER_BASH_ATTRACTION_ATTRACTION_MENU = "Blaziken's Boulder Bash Attraction - Attraction Menu"
BULBASAUR_S_DARING_DASH_ATTRACTION_ATTRACTION_MENU = "Bulbasaur's Daring Dash Attraction - Attraction Menu"
CAVERN_ARON_ERRAND_FRIENDSHIP = 'Cavern Aron - Errand -- Friendship'
CAVERN_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Cavern Bonsly - Hide and Seek Power Competition -- Friendship'
CAVERN_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_UNLOCKS = 'Cavern Bonsly - Hide and Seek Power Competition -- Unlocks'
CAVERN_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Cavern Chimchar - Battle Power Competition -- Friendship'
CAVERN_GEODUDE_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Cavern Geodude - Hide and Seek Power Competition -- Friendship'
CAVERN_MAROWAK_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Cavern Marowak - Battle Power Competition -- Friendship'
CAVERN_MEOWTH_QUIZ_POWER_COMPETITION_FRIENDSHIP = 'Cavern Meowth - Quiz Power Competition -- Friendship'
CAVERN_RAICHU_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Cavern Raichu - Chase Power Competition -- Friendship'
CAVERN_SUDOWOODO_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Cavern Sudowoodo - Hide and Seek Power Competition -- Friendship'
CAVERN_TEDDIURSA_QUIZ_POWER_COMPETITION_FRIENDSHIP = 'Cavern Teddiursa - Quiz Power Competition -- Friendship'
CAVERN_TORCHIC_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Cavern Torchic - Battle Power Competition -- Friendship'
CAVERN_ZONE_MAIN_AREA_ARON = 'Cavern Zone Main Area - Aron'
CAVERN_ZONE_MAIN_AREA_BASTIODON_ATTRACTION = 'Cavern Zone Main Area - Bastiodon Attraction'
CAVERN_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Beach Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_BONSLY = 'Cavern Zone Main Area - Bonsly'
CAVERN_ZONE_MAIN_AREA_BONSLY_UNLOCKS = 'Cavern Zone Main Area - Bonsly Unlocks'
CAVERN_ZONE_MAIN_AREA_CHIMCHAR = 'Cavern Zone Main Area - Chimchar'
CAVERN_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Flower Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_GEODUDE = 'Cavern Zone Main Area - Geodude'
CAVERN_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Granite Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Haunted Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Ice Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Magma Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_MAGMA_ZONE_TRUCK = 'Cavern Zone Main Area - Magma Zone Truck'
CAVERN_ZONE_MAIN_AREA_MAROWAK = 'Cavern Zone Main Area - Marowak'
CAVERN_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Meadow Drifblim Fast Travel'
CAVERN_ZONE_MAIN_AREA_MEOWTH = 'Cavern Zone Main Area - Meowth'
CAVERN_ZONE_MAIN_AREA_RAICHU = 'Cavern Zone Main Area - Raichu'
CAVERN_ZONE_MAIN_AREA_SUDOWOODO = 'Cavern Zone Main Area - Sudowoodo'
CAVERN_ZONE_MAIN_AREA_TEDDIURSA = 'Cavern Zone Main Area - Teddiursa'
CAVERN_ZONE_MAIN_AREA_TORCHIC = 'Cavern Zone Main Area - Torchic'
CAVERN_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION = 'Cavern Zone Main Area - Treehouse Connection'
CAVERN_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Cavern Zone Main Area - Treehouse Drifblim Fast Travel'
DUSKNOIR_S_SPEED_SLAM_ATTRACTION_ATTRACTION_MENU = "Dusknoir's Speed Slam Attraction - Attraction Menu"
EMPOLEON_S_SNOW_SLIDE_ATTRACTION_ATTRACTION_MENU = "Empoleon's Snow Slide Attraction - Attraction Menu"
FLOWER_FURRET_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Flower Furret - Hide and Seek Power Competition -- Friendship'
FLOWER_MEDITITE_QUIZ_POWER_COMPETITION_FRIENDSHIP = 'Flower Meditite - Quiz Power Competition -- Friendship'
FLOWER_TEDDIURSA_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Flower Teddiursa - Chase Power Competition -- Friendship'
FLOWER_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Beach Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Cavern Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_FURRET = 'Flower Zone Main Area - Furret'
FLOWER_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Granite Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_GRANITE_ZONE_GATE = 'Flower Zone Main Area - Granite Zone Gate'
FLOWER_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Haunted Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Ice Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Magma Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Meadow Drifblim Fast Travel'
FLOWER_ZONE_MAIN_AREA_MEDITITE = 'Flower Zone Main Area - Meditite'
FLOWER_ZONE_MAIN_AREA_RAYQUAZA_ATTRACTION = 'Flower Zone Main Area - Rayquaza Attraction'
FLOWER_ZONE_MAIN_AREA_TEDDIURSA = 'Flower Zone Main Area - Teddiursa'
FLOWER_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Flower Zone Main Area - Treehouse Drifblim Fast Travel'
GRANITE_BALTOY_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Granite Baltoy - Battle Power Competition -- Friendship'
GRANITE_BALTOY_BATTLE_POWER_COMPETITION_UNLOCKS = 'Granite Baltoy - Battle Power Competition -- Unlocks'
GRANITE_CLAYDOL_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Granite Claydol - Battle Power Competition -- Friendship'
GRANITE_DRIFLOON_FRIENDSHIP = 'Granite Drifloon - Friendship'
GRANITE_FURRET_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Granite Furret - Hide and Seek Power Competition -- Friendship'
GRANITE_MAROWAK_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Granite Marowak - Battle Power Competition -- Friendship'
GRANITE_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Granite Taillow - Chase Power Competition -- Friendship'
GRANITE_ZONE_MAIN_AREA_ABSOL_ATTRACTION = 'Granite Zone Main Area - Absol Attraction'
GRANITE_ZONE_MAIN_AREA_BALTOY = 'Granite Zone Main Area - Baltoy'
GRANITE_ZONE_MAIN_AREA_BALTOY_UNLOCKS = 'Granite Zone Main Area - Baltoy Unlocks'
GRANITE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Beach Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Cavern Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_CLAYDOL = 'Granite Zone Main Area - Claydol'
GRANITE_ZONE_MAIN_AREA_DRIFLOON = 'Granite Zone Main Area - Drifloon'
GRANITE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Flower Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_FLOWER_ZONE_GATE = 'Granite Zone Main Area - Flower Zone Gate'
GRANITE_ZONE_MAIN_AREA_FURRET = 'Granite Zone Main Area - Furret'
GRANITE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Haunted Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Ice Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Magma Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_MAROWAK = 'Granite Zone Main Area - Marowak'
GRANITE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Meadow Drifblim Fast Travel'
GRANITE_ZONE_MAIN_AREA_SALAMENCE_ATTRACTION = 'Granite Zone Main Area - Salamence Attraction'
GRANITE_ZONE_MAIN_AREA_TAILLOW = 'Granite Zone Main Area - Taillow'
GRANITE_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION = 'Granite Zone Main Area - Treehouse Connection'
GRANITE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Granite Zone Main Area - Treehouse Drifblim Fast Travel'
GYARADOS_AQUA_DASH_ATTRACTION_ATTRACTION_MENU = "Gyarados' Aqua Dash Attraction - Attraction Menu"
HAUNTED_ABRA_FRIENDSHIP = 'Haunted Abra - Friendship'
HAUNTED_AIPOM_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Haunted Aipom - Chase Power Competition -- Friendship'
HAUNTED_AIPOM_CHASE_POWER_COMPETITION_UNLOCKS = 'Haunted Aipom - Chase Power Competition -- Unlocks'
HAUNTED_AMBIPOM_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Haunted Ambipom - Battle Power Competition -- Friendship'
HAUNTED_DRIFLOON_FRIENDSHIP = 'Haunted Drifloon - Friendship'
HAUNTED_MEOWTH_QUIZ_POWER_COMPETITION_FRIENDSHIP = 'Haunted Meowth - Quiz Power Competition -- Friendship'
HAUNTED_RAICHU_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Haunted Raichu - Chase Power Competition -- Friendship'
HAUNTED_RIOLU_BATTLE_POWER_COMPETITION = 'Haunted Riolu - Battle Power Competition'
HAUNTED_ZONE_BOOKSHELF_AREA_HIDDEN_BOOKSHELF = 'Haunted Zone Bookshelf Area - Hidden Bookshelf'
HAUNTED_ZONE_BOOKSHELF_AREA_ROTOM_CONNECTION = 'Haunted Zone Bookshelf Area - Rotom Connection'
HAUNTED_ZONE_MAIN_AREA_AIPOM = 'Haunted Zone Main Area - Aipom'
HAUNTED_ZONE_MAIN_AREA_AIPOM_UNLOCKS = 'Haunted Zone Main Area - Aipom Unlocks'
HAUNTED_ZONE_MAIN_AREA_AMBIPOM = 'Haunted Zone Main Area - Ambipom'
HAUNTED_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Beach Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Cavern Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_DRIFLOON = 'Haunted Zone Main Area - Drifloon'
HAUNTED_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Flower Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Granite Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Ice Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Magma Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_MANSION_GATE = 'Haunted Zone Main Area - Mansion Gate'
HAUNTED_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Meadow Drifblim Fast Travel'
HAUNTED_ZONE_MAIN_AREA_MEOWTH = 'Haunted Zone Main Area - Meowth'
HAUNTED_ZONE_MAIN_AREA_RAICHU = 'Haunted Zone Main Area - Raichu'
HAUNTED_ZONE_MAIN_AREA_RIOLU = 'Haunted Zone Main Area - Riolu'
HAUNTED_ZONE_MAIN_AREA_TANGROWTH_ATTRACTION = 'Haunted Zone Main Area - Tangrowth Attraction'
HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION = 'Haunted Zone Main Area - Treehouse Connection'
HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Haunted Zone Main Area - Treehouse Drifblim Fast Travel'
HAUNTED_ZONE_MANSION_ANTIC_AREA_ABRA = 'Haunted Zone Mansion Antic Area - Abra'
HAUNTED_ZONE_MANSION_ANTIC_AREA_GREEN_GEM_DOOR = 'Haunted Zone Mansion Antic Area - Green Gem Door'
HAUNTED_ZONE_MANSION_AREA_BLUE_GEM_DOOR = 'Haunted Zone Mansion Area - Blue Gem Door'
HAUNTED_ZONE_MANSION_AREA_DUSKNOIR_ATTRACTION = 'Haunted Zone Mansion Area - Dusknoir Attraction'
HAUNTED_ZONE_MANSION_AREA_GREEN_GEM_DOOR = 'Haunted Zone Mansion Area - Green Gem Door'
HAUNTED_ZONE_MANSION_AREA_MAIN_AREA_GATE = 'Haunted Zone Mansion Area - Main Area Gate'
HAUNTED_ZONE_MANSION_AREA_RED_GEM_DOOR = 'Haunted Zone Mansion Area - Red Gem Door'
HAUNTED_ZONE_MANSION_AREA_RIOLU = 'Haunted Zone Mansion Area - Riolu'
HAUNTED_ZONE_MANSION_AREA_WHITE_GEM_DOOR = 'Haunted Zone Mansion Area - White Gem Door'
HAUNTED_ZONE_MANSION_BALLROOM_AREA_DRIFLOON = 'Haunted Zone Mansion Ballroom Area - Drifloon'
HAUNTED_ZONE_MANSION_BALLROOM_AREA_WHITE_GEM_DOOR = 'Haunted Zone Mansion Ballroom Area - White Gem Door'
HAUNTED_ZONE_MANSION_GENGAR_AREA_BLUE_GEM_DOOR = 'Haunted Zone Mansion Gengar Area - Blue Gem Door'
HAUNTED_ZONE_MANSION_STUDY_AREA_HIDDEN_BOOKSHELF = 'Haunted Zone Mansion Study Area - Hidden Bookshelf'
HAUNTED_ZONE_MANSION_STUDY_AREA_RED_GEM_DOOR = 'Haunted Zone Mansion Study Area - Red Gem Door'
HAUNTED_ZONE_ROTOM_AREA_BOOKSHELF_AREA_CONNECTION = 'Haunted Zone Rotom Area - Bookshelf Area Connection'
HAUNTED_ZONE_ROTOM_AREA_ROTOM_ATTRACTION = 'Haunted Zone Rotom Area - Rotom Attraction'
ICE_CORPHISH_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Ice Corphish - Battle Power Competition -- Friendship'
ICE_KRABBY_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Ice Krabby - Chase Power Competition -- Friendship'
ICE_MUDKIP_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Ice Mudkip - Hide and Seek Power Competition -- Friendship'
ICE_STARAVIA_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Ice Staravia - Battle Power Competition -- Friendship'
ICE_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Ice Starly - Chase Power Competition -- Friendship'
ICE_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Ice Taillow - Chase Power Competition -- Friendship'
ICE_TEDDIURSA_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Ice Teddiursa - Chase Power Competition -- Friendship'
ICE_WINGULL_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Ice Wingull - Chase Power Competition -- Friendship'
ICE_ZONE_EMPOLEON_AREA_EMPOLEON_ATTRACTION = 'Ice Zone Empoleon Area - Empoleon Attraction'
ICE_ZONE_EMPOLEON_AREA_ICE_ZONE_MAIN_GATE = 'Ice Zone Empoleon Area - Ice Zone Main Gate'
ICE_ZONE_FROZEN_LAKE_AREA_FROZEN_LAKE = 'Ice Zone Frozen Lake Area - Frozen Lake'
ICE_ZONE_LOWER_LIFT_AREA_CORPHISH = 'Ice Zone Lower Lift Area - Corphish'
ICE_ZONE_LOWER_LIFT_AREA_LOWER_LIFT = 'Ice Zone Lower Lift Area - Lower Lift'
ICE_ZONE_LOWER_LIFT_AREA_WINGULL = 'Ice Zone Lower Lift Area - Wingull'
ICE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Beach Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Cavern Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_EMPOLEON_GATE = 'Ice Zone Main Area - Empoleon Gate'
ICE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Flower Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_FROZEN_LAKE = 'Ice Zone Main Area - Frozen Lake'
ICE_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Granite Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Haunted Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_ICE_ZONE_LAPRAS = 'Ice Zone Main Area - Ice Zone Lapras'
ICE_ZONE_MAIN_AREA_KRABBY = 'Ice Zone Main Area - Krabby'
ICE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Magma Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Meadow Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_MUDKIP = 'Ice Zone Main Area - Mudkip'
ICE_ZONE_MAIN_AREA_STARAVIA = 'Ice Zone Main Area - Staravia'
ICE_ZONE_MAIN_AREA_STARLY = 'Ice Zone Main Area - Starly'
ICE_ZONE_MAIN_AREA_TAILLOW = 'Ice Zone Main Area - Taillow'
ICE_ZONE_MAIN_AREA_TEDDIURSA = 'Ice Zone Main Area - Teddiursa'
ICE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Ice Zone Main Area - Treehouse Drifblim Fast Travel'
ICE_ZONE_MAIN_AREA_UPPER_LIFT = 'Ice Zone Main Area - Upper Lift'
MAGMA_ARON_ERRAND_FRIENDSHIP = 'Magma Aron - Errand -- Friendship'
MAGMA_BALTOY_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Magma Baltoy - Battle Power Competition -- Friendship'
MAGMA_BALTOY_BATTLE_POWER_COMPETITION_UNLOCKS = 'Magma Baltoy - Battle Power Competition -- Unlocks'
MAGMA_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Magma Bonsly - Hide and Seek Power Competition -- Friendship'
MAGMA_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Magma Chimchar - Battle Power Competition -- Friendship'
MAGMA_CLAYDOL_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Magma Claydol - Battle Power Competition -- Friendship'
MAGMA_GEODUDE_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Magma Geodude - Hide and Seek Power Competition -- Friendship'
MAGMA_MEDITITE_QUIZ_POWER_COMPETITION_FRIENDSHIP = 'Magma Meditite - Quiz Power Competition -- Friendship'
MAGMA_TORCHIC_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Magma Torchic - Battle Power Competition -- Friendship'
MAGMA_ZONE_BLAZIKEN_AREA_BLAZIKEN_ATTRACTION = 'Magma Zone Blaziken Area - Blaziken Attraction'
MAGMA_ZONE_BLAZIKEN_AREA_MAIN_AREA_GATE = 'Magma Zone Blaziken Area - Main Area Gate'
MAGMA_ZONE_CIRCLE_AREA_MAGCARGO_AREA_BRIDGE = 'Magma Zone Circle Area - Magcargo Area Bridge'
MAGMA_ZONE_CIRCLE_AREA_MAIN_AREA_FIRE_WALL = 'Magma Zone Circle Area - Main Area Fire Wall'
MAGMA_ZONE_CIRCLE_AREA_MEDITITE = 'Magma Zone Circle Area - Meditite'
MAGMA_ZONE_CIRCLE_AREA_RHYPERIOR_ATTRACTION = 'Magma Zone Circle Area - Rhyperior Attraction'
MAGMA_ZONE_MAGCARGO_AREA_BLAZIKEN_GATE = 'Magma Zone Magcargo Area - Blaziken Gate'
MAGMA_ZONE_MAGCARGO_AREA_MAIN_AREA_BRIDGE = 'Magma Zone Magcargo Area - Main Area Bridge'
MAGMA_ZONE_MAIN_AREA_ARON = 'Magma Zone Main Area - Aron'
MAGMA_ZONE_MAIN_AREA_BALTOY = 'Magma Zone Main Area - Baltoy'
MAGMA_ZONE_MAIN_AREA_BALTOY_UNLOCKS = 'Magma Zone Main Area - Baltoy Unlocks'
MAGMA_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Beach Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_BONSLY = 'Magma Zone Main Area - Bonsly'
MAGMA_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Cavern Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_CAVERN_ZONE_TRUCK = 'Magma Zone Main Area - Cavern Zone Truck'
MAGMA_ZONE_MAIN_AREA_CHIMCHAR = 'Magma Zone Main Area - Chimchar'
MAGMA_ZONE_MAIN_AREA_CIRCLE_AREA_FIRE_WALL = 'Magma Zone Main Area - Circle Area Fire Wall'
MAGMA_ZONE_MAIN_AREA_CLAYDOL = 'Magma Zone Main Area - Claydol'
MAGMA_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Flower Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_GEODUDE = 'Magma Zone Main Area - Geodude'
MAGMA_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Granite Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Haunted Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Ice Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Meadow Drifblim Fast Travel'
MAGMA_ZONE_MAIN_AREA_TORCHIC = 'Magma Zone Main Area - Torchic'
MAGMA_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Magma Zone Main Area - Treehouse Drifblim Fast Travel'
MANSION_DRIFLOON_FRIENDSHIP = 'Mansion Drifloon - Friendship'
MANSION_RIOLU_BATTLE_POWER_COMPETITION = 'Mansion Riolu - Battle Power Competition'
MEADOW_AIPOM_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Meadow Aipom - Chase Power Competition -- Friendship'
MEADOW_AIPOM_CHASE_POWER_COMPETITION_UNLOCKS = 'Meadow Aipom - Chase Power Competition -- Unlocks'
MEADOW_AMBIPOM_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Meadow Ambipom - Battle Power Competition -- Friendship'
MEADOW_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Meadow Bonsly - Hide and Seek Power Competition -- Friendship'
MEADOW_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_UNLOCKS = 'Meadow Bonsly - Hide and Seek Power Competition -- Unlocks'
MEADOW_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Meadow Chimchar - Battle Power Competition -- Friendship'
MEADOW_SPEAROW_BATTLE_POWER_COMPETITION_FRIENDSHIP = 'Meadow Spearow - Battle Power Competition -- Friendship'
MEADOW_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP = 'Meadow Starly - Chase Power Competition -- Friendship'
MEADOW_SUDOWOODO_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP = 'Meadow Sudowoodo - Hide and Seek Power Competition -- Friendship'
MEADOW_ZONE_MAIN_AREA_AIPOM = 'Meadow Zone Main Area - Aipom'
MEADOW_ZONE_MAIN_AREA_AIPOM_UNLOCKS = 'Meadow Zone Main Area - Aipom Unlocks'
MEADOW_ZONE_MAIN_AREA_AMBIPOM = 'Meadow Zone Main Area - Ambipom'
MEADOW_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Beach Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_BONSLY = 'Meadow Zone Main Area - Bonsly'
MEADOW_ZONE_MAIN_AREA_BONSLY_UNLOCKS = 'Meadow Zone Main Area - Bonsly Unlocks'
MEADOW_ZONE_MAIN_AREA_BULBASAUR_ATTRACTION = 'Meadow Zone Main Area - Bulbasaur Attraction'
MEADOW_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Cavern Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_CHIMCHAR = 'Meadow Zone Main Area - Chimchar'
MEADOW_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Flower Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Granite Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Haunted Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Ice Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Magma Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_POKEPARK_ENTRANCE_GATE = 'Meadow Zone Main Area - Pokepark Entrance Gate'
MEADOW_ZONE_MAIN_AREA_SPEAROW = 'Meadow Zone Main Area - Spearow'
MEADOW_ZONE_MAIN_AREA_STARLY = 'Meadow Zone Main Area - Starly'
MEADOW_ZONE_MAIN_AREA_SUDOWOODO = 'Meadow Zone Main Area - Sudowoodo'
MEADOW_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION = 'Meadow Zone Main Area - Treehouse Connection'
MEADOW_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL = 'Meadow Zone Main Area - Treehouse Drifblim Fast Travel'
MEADOW_ZONE_MAIN_AREA_VENUSAUR_GATE = 'Meadow Zone Main Area - Venusaur Gate'
MEADOW_ZONE_VENUSAUR_AREA_MEADOW_ZONE_MAIN_GATE = 'Meadow Zone Venusaur Area - Meadow Zone Main Gate'
MEADOW_ZONE_VENUSAUR_AREA_VENUSAUR_ATTRACTION = 'Meadow Zone Venusaur Area - Venusaur Attraction'
PELIPPER_S_CIRCLE_CIRCUIT_ATTRACTION_ATTRACTION_MENU = "Pelipper's Circle Circuit Attraction - Attraction Menu"
POKEPARK_ENTRANCE_MEADOW_ZONE_GATE = 'Pokepark Entrance - Meadow Zone Gate'
RAYQUAZA_S_BALLOON_PANIC_ATTRACTION_ATTRACTION_MENU = "Rayquaza's Balloon Panic Attraction - Attraction Menu"
RHYPERIOR_S_BUMPER_BURN_ATTRACTION_ATTRACTION_MENU = "Rhyperior's Bumper Burn Attraction - Attraction Menu"
ROTOM_S_SPOOKY_SHOOT_EM_UP_ATTRACTION_ATTRACTION_MENU = "Rotom's Spooky Shoot-'em-Up Attraction - Attraction Menu"
SALAMENCE_S_SKY_RACE_ATTRACTION_ATTRACTION_MENU = "Salamence's Sky Race Attraction - Attraction Menu"
SKYGARDEN_PIPLUP_SKYBALLOON = 'Skygarden - Piplup Skyballoon'
TANGROWTH_S_SWING_ALONG_ATTRACTION_ATTRACTION_MENU = "Tangrowth's Swing-Along Attraction - Attraction Menu"
TREEHOUSE_ABRA = 'Treehouse - Abra'
TREEHOUSE_BEACH_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Beach Drifblim Fast Travel'
TREEHOUSE_BEACH_ZONE_GATE = 'Treehouse - Beach Zone Gate'
TREEHOUSE_CAVERN_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Cavern Drifblim Fast Travel'
TREEHOUSE_CAVERN_ZONE_GATE = 'Treehouse - Cavern Zone Gate'
TREEHOUSE_FLOWER_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Flower Drifblim Fast Travel'
TREEHOUSE_GRANITE_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Granite Drifblim Fast Travel'
TREEHOUSE_GRANITE_ZONE_GATE = 'Treehouse - Granite Zone Gate'
TREEHOUSE_HAUNTED_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Haunted Drifblim Fast Travel'
TREEHOUSE_HAUNTED_ZONE_GATE = 'Treehouse - Haunted Zone Gate'
TREEHOUSE_ICE_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Ice Drifblim Fast Travel'
TREEHOUSE_MAGMA_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Magma Drifblim Fast Travel'
TREEHOUSE_MEADOW_DRIFBLIM_FAST_TRAVEL = 'Treehouse - Meadow Drifblim Fast Travel'
TREEHOUSE_MEADOW_ZONE_GATE = 'Treehouse - Meadow Zone Gate'
TREEHOUSE_PIPLUP_SKYBALLOON = 'Treehouse - Piplup Skyballoon'
TREEHOUSE_ABRA_FRIENDSHIP = 'Treehouse Abra - Friendship'
TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_CONNECTION = 'Treehouse Beach Passage - Beach Zone Connection'
TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_GATE = 'Treehouse Beach Passage - Beach Zone Gate'
TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_CONNECTION = 'Treehouse Cavern Passage - Cavern Zone Connection'
TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_GATE = 'Treehouse Cavern Passage - Cavern Zone Gate'
TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_CONNECTION = 'Treehouse Granite Passage - Granite Zone Connection'
TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_GATE = 'Treehouse Granite Passage - Granite Zone Gate'
TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_CONNECTION = 'Treehouse Haunted Passage - Haunted Zone Connection'
TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_GATE = 'Treehouse Haunted Passage - Haunted Zone Gate'
TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_CONNECTION = 'Treehouse Meadow Passage - Meadow Zone Connection'
TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_GATE = 'Treehouse Meadow Passage - Meadow Zone Gate'
VENUSAUR_S_VINE_SWING_ATTRACTION_ATTRACTION_MENU = "Venusaur's Vine Swing Attraction - Attraction Menu"

__all__ = [
    "GRANITE_BALTOY_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "HAUNTED_DRIFLOON_FRIENDSHIP",
    "FLOWER_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ABRA_FRIENDSHIP",
    "MAGMA_ZONE_MAIN_AREA_CIRCLE_AREA_FIRE_WALL",
    "ICE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_BOOKSHELF_AREA_ROTOM_CONNECTION",
    "GRANITE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "ICE_CORPHISH_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_HAUNTED_ZONE_GATE",
    "HAUNTED_ZONE_MANSION_GENGAR_AREA_BLUE_GEM_DOOR",
    "HAUNTED_ZONE_MANSION_ANTIC_AREA_ABRA",
    "BULBASAUR_S_DARING_DASH_ATTRACTION_ATTRACTION_MENU",
    "CAVERN_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_CONNECTION",
    "HAUNTED_ZONE_MAIN_AREA_RIOLU",
    "HAUNTED_ZONE_MANSION_AREA_MAIN_AREA_GATE",
    "FLOWER_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_BALTOY_BATTLE_POWER_COMPETITION_UNLOCKS",
    "MEADOW_ZONE_MAIN_AREA_BONSLY",
    "TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_GATE",
    "BEACH_ZONE_MAIN_AREA_TAILLOW",
    "ICE_ZONE_MAIN_AREA_MUDKIP",
    "HAUNTED_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_ZONE_MAGCARGO_AREA_BLAZIKEN_GATE",
    "BEACH_ZONE_MAIN_AREA_STARAVIA",
    "HAUNTED_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_BALLROOM_AREA_DRIFLOON",
    "MEADOW_ZONE_MAIN_AREA_AMBIPOM",
    "MEADOW_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "POKEPARK_ENTRANCE_MEADOW_ZONE_GATE",
    "TREEHOUSE_ABRA",
    "CAVERN_MAROWAK_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "BEACH_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_SUDOWOODO_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "GRANITE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_ZONE_MAIN_AREA_ARON",
    "BEACH_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_FURRET_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "TANGROWTH_S_SWING_ALONG_ATTRACTION_ATTRACTION_MENU",
    "TREEHOUSE_ICE_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_FROZEN_LAKE_AREA_FROZEN_LAKE",
    "CAVERN_ARON_ERRAND_FRIENDSHIP",
    "FLOWER_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_SUDOWOODO",
    "MAGMA_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_CONNECTION",
    "BEACH_ZONE_MAIN_AREA_MIDDLE_BRIDGE",
    "HAUNTED_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_GATE",
    "ICE_TEDDIURSA_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "DUSKNOIR_S_SPEED_SLAM_ATTRACTION_ATTRACTION_MENU",
    "FLOWER_TEDDIURSA_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_CONNECTION",
    "MEADOW_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "CAVERN_ZONE_MAIN_AREA_CHIMCHAR",
    "GRANITE_ZONE_MAIN_AREA_BALTOY",
    "MAGMA_GEODUDE_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "BEACH_MUDKIP_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "BEACH_ZONE_MAIN_AREA_CORPHISH",
    "MAGMA_ZONE_BLAZIKEN_AREA_BLAZIKEN_ATTRACTION",
    "MEADOW_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_BULBASAUR_ATTRACTION",
    "HAUNTED_ZONE_MAIN_AREA_RAICHU",
    "ROTOM_S_SPOOKY_SHOOT_EM_UP_ATTRACTION_ATTRACTION_MENU",
    "ICE_ZONE_MAIN_AREA_STARLY",
    "BEACH_SPEAROW_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "ICE_KRABBY_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "ICE_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_SPEAROW",
    "BLAZIKEN_S_BOULDER_BASH_ATTRACTION_ATTRACTION_MENU",
    "MAGMA_ZONE_MAIN_AREA_CLAYDOL",
    "MEADOW_AIPOM_CHASE_POWER_COMPETITION_UNLOCKS",
    "TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_CONNECTION",
    "HAUNTED_MEOWTH_QUIZ_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_SPEAROW_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_GEODUDE",
    "ICE_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "ICE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "RAYQUAZA_S_BALLOON_PANIC_ATTRACTION_ATTRACTION_MENU",
    "GRANITE_ZONE_MAIN_AREA_FURRET",
    "GRANITE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_BALTOY_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_AIPOM_UNLOCKS",
    "MAGMA_ZONE_MAIN_AREA_GEODUDE",
    "CAVERN_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_MAIN_AREA_UPPER_LIFT",
    "HAUNTED_RAICHU_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "GRANITE_ZONE_MAIN_AREA_CLAYDOL",
    "FLOWER_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_KRABBY",
    "ICE_ZONE_LOWER_LIFT_AREA_CORPHISH",
    "TREEHOUSE_GRANITE_ZONE_GATE",
    "CAVERN_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_MANSION_GATE",
    "MAGMA_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "FLOWER_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_LOWER_LIFT_AREA_WINGULL",
    "MAGMA_ARON_ERRAND_FRIENDSHIP",
    "BEACH_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_AREA_RIOLU",
    "BEACH_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "BEACH_KRABBY_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "BEACH_ZONE_RECYCLE_AREA_GYARADOS_ATTRACTION",
    "MEADOW_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "CAVERN_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_AREA_BLUE_GEM_DOOR",
    "MEADOW_ZONE_MAIN_AREA_VENUSAUR_GATE",
    "HAUNTED_ZONE_MAIN_AREA_DRIFLOON",
    "CAVERN_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION",
    "MEADOW_ZONE_MAIN_AREA_POKEPARK_ENTRANCE_GATE",
    "CAVERN_ZONE_MAIN_AREA_BONSLY_UNLOCKS",
    "BEACH_ZONE_MAIN_AREA_MUDKIP",
    "FLOWER_FURRET_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "MAGMA_ZONE_MAIN_AREA_CHIMCHAR",
    "PELIPPER_S_CIRCLE_CIRCUIT_ATTRACTION_ATTRACTION_MENU",
    "GRANITE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_AREA_GREEN_GEM_DOOR",
    "MAGMA_CLAYDOL_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_ABRA_FRIENDSHIP",
    "BEACH_ZONE_LAPRAS_AREA_BEACH_ZONE_LAPRAS",
    "TREEHOUSE_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_PELIPPER_ATTRACTION",
    "MANSION_DRIFLOON_FRIENDSHIP",
    "MEADOW_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_UNLOCKS",
    "HAUNTED_ZONE_MANSION_AREA_WHITE_GEM_DOOR",
    "BEACH_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "CAVERN_ZONE_MAIN_AREA_RAICHU",
    "HAUNTED_ZONE_ROTOM_AREA_ROTOM_ATTRACTION",
    "FLOWER_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_STARLY",
    "ICE_ZONE_EMPOLEON_AREA_ICE_ZONE_MAIN_GATE",
    "BEACH_ZONE_LAPRAS_AREA_MAIN_AREA_ROCK",
    "SKYGARDEN_PIPLUP_SKYBALLOON",
    "GRANITE_ZONE_MAIN_AREA_MAROWAK",
    "MAGMA_ZONE_MAGCARGO_AREA_MAIN_AREA_BRIDGE",
    "GRANITE_ZONE_MAIN_AREA_SALAMENCE_ATTRACTION",
    "MAGMA_ZONE_MAIN_AREA_BONSLY",
    "GRANITE_ZONE_MAIN_AREA_FLOWER_ZONE_GATE",
    "HAUNTED_ZONE_MANSION_ANTIC_AREA_GREEN_GEM_DOOR",
    "HAUNTED_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_GATE",
    "BEACH_ZONE_RECYCLE_AREA_MAIN_BRIDGE",
    "MEADOW_ZONE_VENUSAUR_AREA_MEADOW_ZONE_MAIN_GATE",
    "HAUNTED_ZONE_ROTOM_AREA_BOOKSHELF_AREA_CONNECTION",
    "CAVERN_MEOWTH_QUIZ_POWER_COMPETITION_FRIENDSHIP",
    "HAUNTED_ZONE_MANSION_AREA_RED_GEM_DOOR",
    "CAVERN_ZONE_MAIN_AREA_TEDDIURSA",
    "MEADOW_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_MAIN_AREA_ICE_ZONE_LAPRAS",
    "MAGMA_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "ABSOL_S_HURDLE_BOUNCE_ATTRACTION_ATTRACTION_MENU",
    "ICE_ZONE_MAIN_AREA_KRABBY",
    "GRANITE_ZONE_MAIN_AREA_DRIFLOON",
    "ICE_STARAVIA_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "GYARADOS_AQUA_DASH_ATTRACTION_ATTRACTION_MENU",
    "HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "GRANITE_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION",
    "CAVERN_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_MEOWTH",
    "ICE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "BEACH_WINGULL_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_AMBIPOM_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_AIPOM_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_AMBIPOM_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "HAUNTED_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_AIPOM",
    "MAGMA_ZONE_CIRCLE_AREA_MAIN_AREA_FIRE_WALL",
    "FLOWER_ZONE_MAIN_AREA_GRANITE_ZONE_GATE",
    "MEADOW_ZONE_MAIN_AREA_CHIMCHAR",
    "HAUNTED_ZONE_MANSION_STUDY_AREA_RED_GEM_DOOR",
    "TREEHOUSE_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "ICE_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "HAUNTED_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_STUDY_AREA_HIDDEN_BOOKSHELF",
    "MAGMA_ZONE_CIRCLE_AREA_RHYPERIOR_ATTRACTION",
    "TREEHOUSE_BEACH_DRIFBLIM_FAST_TRAVEL",
    "RHYPERIOR_S_BUMPER_BURN_ATTRACTION_ATTRACTION_MENU",
    "BEACH_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "FLOWER_ZONE_MAIN_AREA_FURRET",
    "GRANITE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION",
    "MAGMA_MEDITITE_QUIZ_POWER_COMPETITION_FRIENDSHIP",
    "MAGMA_ZONE_BLAZIKEN_AREA_MAIN_AREA_GATE",
    "MAGMA_ZONE_MAIN_AREA_TORCHIC",
    "CAVERN_ZONE_MAIN_AREA_MAGMA_ZONE_TRUCK",
    "BEACH_ZONE_MAIN_AREA_RECYCLE_BRIDGE",
    "TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_GATE",
    "ICE_ZONE_MAIN_AREA_TEDDIURSA",
    "MAGMA_ZONE_MAIN_AREA_BALTOY",
    "MAGMA_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_MAROWAK",
    "TREEHOUSE_MEADOW_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MANSION_BALLROOM_AREA_WHITE_GEM_DOOR",
    "HAUNTED_ZONE_MAIN_AREA_TANGROWTH_ATTRACTION",
    "BEACH_CORPHISH_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_BASTIODON_ATTRACTION",
    "EMPOLEON_S_SNOW_SLIDE_ATTRACTION_ATTRACTION_MENU",
    "GRANITE_MAROWAK_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_STARLY_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "HAUNTED_AIPOM_CHASE_POWER_COMPETITION_UNLOCKS",
    "FLOWER_ZONE_MAIN_AREA_TEDDIURSA",
    "CAVERN_TEDDIURSA_QUIZ_POWER_COMPETITION_FRIENDSHIP",
    "FLOWER_MEDITITE_QUIZ_POWER_COMPETITION_FRIENDSHIP",
    "FLOWER_ZONE_MAIN_AREA_MEDITITE",
    "MEADOW_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_AMBIPOM",
    "CAVERN_GEODUDE_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "BEACH_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_TORCHIC_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "MEADOW_SUDOWOODO_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "MANSION_RIOLU_BATTLE_POWER_COMPETITION",
    "MAGMA_ZONE_MAIN_AREA_CAVERN_ZONE_TRUCK",
    "GRANITE_ZONE_MAIN_AREA_ABSOL_ATTRACTION",
    "TREEHOUSE_BEACH_ZONE_GATE",
    "ICE_WINGULL_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_TORCHIC_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_TORCHIC",
    "BEACH_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL",
    "CAVERN_ZONE_MAIN_AREA_SUDOWOODO",
    "CAVERN_ZONE_MAIN_AREA_BONSLY",
    "CAVERN_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_RAICHU_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION",
    "BEACH_ZONE_MAIN_AREA_WINGULL",
    "ICE_ZONE_EMPOLEON_AREA_EMPOLEON_ATTRACTION",
    "HAUNTED_ZONE_MAIN_AREA_AIPOM_UNLOCKS",
    "MEADOW_ZONE_MAIN_AREA_BONSLY_UNLOCKS",
    "TREEHOUSE_PIPLUP_SKYBALLOON",
    "ICE_ZONE_MAIN_AREA_STARAVIA",
    "TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_CONNECTION",
    "VENUSAUR_S_VINE_SWING_ATTRACTION_ATTRACTION_MENU",
    "MAGMA_ZONE_CIRCLE_AREA_MEDITITE",
    "ICE_ZONE_MAIN_AREA_EMPOLEON_GATE",
    "BEACH_ZONE_MAIN_AREA_LAPRAS_AREA_ROCK",
    "MEADOW_ZONE_MAIN_AREA_SPEAROW",
    "HAUNTED_AIPOM_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "MAGMA_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "FLOWER_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_STARLY",
    "CAVERN_ZONE_MAIN_AREA_ARON",
    "ICE_MUDKIP_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "MAGMA_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_BALTOY_BATTLE_POWER_COMPETITION_UNLOCKS",
    "ICE_ZONE_MAIN_AREA_FROZEN_LAKE",
    "TREEHOUSE_MEADOW_ZONE_GATE",
    "CAVERN_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "BEACH_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL",
    "CAVERN_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_FRIENDSHIP",
    "GRANITE_DRIFLOON_FRIENDSHIP",
    "CAVERN_ZONE_MAIN_AREA_MEOWTH",
    "MEADOW_ZONE_MAIN_AREA_AIPOM",
    "GRANITE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "MAGMA_ZONE_CIRCLE_AREA_MAGCARGO_AREA_BRIDGE",
    "BEACH_ZONE_MIDDLE_ISLE_MAIN_BRIDGE",
    "FLOWER_ZONE_MAIN_AREA_RAYQUAZA_ATTRACTION",
    "ICE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "BEACH_TAILLOW_CHASE_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION",
    "CAVERN_BONSLY_HIDE_AND_SEEK_POWER_COMPETITION_UNLOCKS",
    "MAGMA_ZONE_MAIN_AREA_BALTOY_UNLOCKS",
    "MAGMA_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_BOOKSHELF_AREA_HIDDEN_BOOKSHELF",
    "GRANITE_ZONE_MAIN_AREA_BALTOY_UNLOCKS",
    "GRANITE_ZONE_MAIN_AREA_TAILLOW",
    "ICE_ZONE_LOWER_LIFT_AREA_LOWER_LIFT",
    "MEADOW_CHIMCHAR_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "TREEHOUSE_CAVERN_ZONE_GATE",
    "TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_GATE",
    "ICE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL",
    "BEACH_STARAVIA_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "MEADOW_ZONE_VENUSAUR_AREA_VENUSAUR_ATTRACTION",
    "GRANITE_CLAYDOL_BATTLE_POWER_COMPETITION_FRIENDSHIP",
    "FLOWER_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL",
    "HAUNTED_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL",
    "ICE_ZONE_MAIN_AREA_TAILLOW",
    "HAUNTED_ZONE_MANSION_AREA_DUSKNOIR_ATTRACTION",
    "HAUNTED_RIOLU_BATTLE_POWER_COMPETITION",
    "BASTIODON_S_PANEL_CRUSH_ATTRACTION_ATTRACTION_MENU",
    "SALAMENCE_S_SKY_RACE_ATTRACTION_ATTRACTION_MENU",
]
