from typing import Final, Literal, TypedDict

from patcher.helper.entrance_exit_names import BEACH_ZONE_LAPRAS_AREA_BEACH_ZONE_LAPRAS, \
    BEACH_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, BEACH_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, \
    BEACH_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    BEACH_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, BEACH_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    BEACH_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, BEACH_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    BEACH_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION, \
    BEACH_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, CAVERN_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, \
    CAVERN_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, CAVERN_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    CAVERN_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, \
    CAVERN_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    CAVERN_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, \
    CAVERN_ZONE_MAIN_AREA_MAGMA_ZONE_TRUCK, \
    CAVERN_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, CAVERN_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION, \
    CAVERN_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, FLOWER_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, \
    FLOWER_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, FLOWER_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    FLOWER_ZONE_MAIN_AREA_GRANITE_ZONE_GATE, \
    FLOWER_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, FLOWER_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    FLOWER_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, \
    FLOWER_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    FLOWER_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, GRANITE_ZONE_MAIN_AREA_FLOWER_ZONE_GATE, \
    GRANITE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, GRANITE_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    GRANITE_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION, \
    GRANITE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, HAUNTED_ZONE_BOOKSHELF_AREA_ROTOM_CONNECTION, \
    HAUNTED_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, \
    HAUNTED_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, HAUNTED_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, \
    HAUNTED_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    HAUNTED_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    HAUNTED_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, HAUNTED_ZONE_MAIN_AREA_MANSION_GATE, \
    HAUNTED_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION, \
    HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, HAUNTED_ZONE_MANSION_AREA_MAIN_AREA_GATE, \
    HAUNTED_ZONE_ROTOM_AREA_BOOKSHELF_AREA_CONNECTION, ICE_ZONE_EMPOLEON_AREA_ICE_ZONE_MAIN_GATE, \
    ICE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, ICE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, \
    ICE_ZONE_MAIN_AREA_EMPOLEON_GATE, ICE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, \
    ICE_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    ICE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, \
    ICE_ZONE_MAIN_AREA_ICE_ZONE_LAPRAS, \
    ICE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, ICE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    ICE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_BLAZIKEN_AREA_MAIN_AREA_GATE, \
    MAGMA_ZONE_MAGCARGO_AREA_BLAZIKEN_GATE, \
    MAGMA_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, MAGMA_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_MAIN_AREA_CAVERN_ZONE_TRUCK, \
    MAGMA_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, MAGMA_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    MAGMA_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL, MEADOW_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL, \
    MEADOW_ZONE_MAIN_AREA_POKEPARK_ENTRANCE_GATE, \
    MEADOW_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION, \
    MEADOW_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL, MEADOW_ZONE_MAIN_AREA_VENUSAUR_GATE, \
    MEADOW_ZONE_VENUSAUR_AREA_MEADOW_ZONE_MAIN_GATE, \
    POKEPARK_ENTRANCE_MEADOW_ZONE_GATE, SKYGARDEN_PIPLUP_SKYBALLOON, TREEHOUSE_BEACH_DRIFBLIM_FAST_TRAVEL, \
    TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_CONNECTION, \
    TREEHOUSE_CAVERN_DRIFBLIM_FAST_TRAVEL, TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_CONNECTION, \
    TREEHOUSE_FLOWER_DRIFBLIM_FAST_TRAVEL, TREEHOUSE_GRANITE_DRIFBLIM_FAST_TRAVEL, \
    TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_CONNECTION, \
    TREEHOUSE_HAUNTED_DRIFBLIM_FAST_TRAVEL, \
    TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_CONNECTION, \
    TREEHOUSE_ICE_DRIFBLIM_FAST_TRAVEL, TREEHOUSE_MAGMA_DRIFBLIM_FAST_TRAVEL, TREEHOUSE_MEADOW_DRIFBLIM_FAST_TRAVEL, \
    TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_CONNECTION, TREEHOUSE_PIPLUP_SKYBALLOON

ZoneKey = Literal["zone", "area", "position"]


class ZoneData(TypedDict):
    zone: int
    area: int
    position: int


exit_to_zone_data: Final[dict[str, ZoneData]] = {
    TREEHOUSE_MEADOW_PASSAGE_MEADOW_ZONE_CONNECTION: {"zone": 2, "area": 1, "position": 0},
    MEADOW_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION: {"zone": 1, "area": 1, "position": 1},

    MEADOW_ZONE_VENUSAUR_AREA_MEADOW_ZONE_MAIN_GATE: {"zone": 1, "area": 2, "position": 0},
    MEADOW_ZONE_MAIN_AREA_VENUSAUR_GATE: {"zone": 1, "area": 1, "position": 2},

    MEADOW_ZONE_MAIN_AREA_POKEPARK_ENTRANCE_GATE: {"zone": 1, "area": 1, "position": 0},
    POKEPARK_ENTRANCE_MEADOW_ZONE_GATE: {"zone": 99, "area": 1, "position": 1},

    BEACH_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION: {"zone": 3, "area": 1, "position": 0},
    TREEHOUSE_BEACH_PASSAGE_BEACH_ZONE_CONNECTION: {"zone": 2, "area": 1, "position": 1},

    ICE_ZONE_MAIN_AREA_ICE_ZONE_LAPRAS: {"zone": 3, "area": 2, "position": 0},
    BEACH_ZONE_LAPRAS_AREA_BEACH_ZONE_LAPRAS: {"zone": 2, "area": 1, "position": 1},

    ICE_ZONE_MAIN_AREA_EMPOLEON_GATE: {"zone": 3, "area": 2, "position": 1},
    ICE_ZONE_EMPOLEON_AREA_ICE_ZONE_MAIN_GATE: {"zone": 3, "area": 3, "position": 0},

    CAVERN_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION: {"zone": 4, "area": 1, "position": 0},
    TREEHOUSE_CAVERN_PASSAGE_CAVERN_ZONE_CONNECTION: {"zone": 2, "area": 1, "position": 2},

    CAVERN_ZONE_MAIN_AREA_MAGMA_ZONE_TRUCK: {"zone": 4, "area": 1, "position": 1},
    MAGMA_ZONE_MAIN_AREA_CAVERN_ZONE_TRUCK: {"zone": 4, "area": 2, "position": 0},

    MAGMA_ZONE_MAGCARGO_AREA_BLAZIKEN_GATE: {"zone": 4, "area": 2, "position": 1},
    MAGMA_ZONE_BLAZIKEN_AREA_MAIN_AREA_GATE: {"zone": 4, "area": 3, "position": 0},

    HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION: {"zone": 5, "area": 1, "position": 0},
    TREEHOUSE_HAUNTED_PASSAGE_HAUNTED_ZONE_CONNECTION: {"zone": 2, "area": 1, "position": 3},

    HAUNTED_ZONE_MAIN_AREA_MANSION_GATE: {"zone": 5, "area": 1, "position": 1},
    HAUNTED_ZONE_MANSION_AREA_MAIN_AREA_GATE: {"zone": 5, "area": 2, "position": 0},

    HAUNTED_ZONE_ROTOM_AREA_BOOKSHELF_AREA_CONNECTION: {"zone": 5, "area": 3, "position": 0},
    HAUNTED_ZONE_BOOKSHELF_AREA_ROTOM_CONNECTION: {"zone": 5, "area": 2, "position": 1},

    GRANITE_ZONE_MAIN_AREA_TREEHOUSE_CONNECTION: {"zone": 6, "area": 1, "position": 0},
    TREEHOUSE_GRANITE_PASSAGE_GRANITE_ZONE_CONNECTION: {"zone": 2, "area": 1, "position": 4},

    FLOWER_ZONE_MAIN_AREA_GRANITE_ZONE_GATE: {"zone": 6, "area": 2, "position": 0},
    GRANITE_ZONE_MAIN_AREA_FLOWER_ZONE_GATE: {"zone": 6, "area": 1, "position": 1},

    TREEHOUSE_PIPLUP_SKYBALLOON: {"zone": 2, "area": 1, "position": 6},
    SKYGARDEN_PIPLUP_SKYBALLOON: {"zone": 7, "area": 1, "position": 0},

    # Fast Travel
    TREEHOUSE_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},
    TREEHOUSE_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 2, "area": 1, "position": 5},

    MEADOW_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},
    MEADOW_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 1, "area": 1, "position": 3},

    BEACH_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},
    BEACH_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 1, "position": 2},

    ICE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},
    ICE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 3, "area": 2, "position": 2},

    CAVERN_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},
    CAVERN_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 1, "position": 2},

    MAGMA_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},
    MAGMA_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 4, "area": 2, "position": 2},

    HAUNTED_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},
    HAUNTED_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 5, "area": 1, "position": 2},

    GRANITE_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},
    GRANITE_ZONE_MAIN_AREA_FLOWER_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 1, "position": 2},

    FLOWER_ZONE_MAIN_AREA_MEADOW_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_TREEHOUSE_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_BEACH_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_ICE_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_CAVERN_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_MAGMA_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_HAUNTED_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},
    FLOWER_ZONE_MAIN_AREA_GRANITE_DRIFBLIM_FAST_TRAVEL: {"zone": 6, "area": 2, "position": 1},

}
