[package]
name = "pokeparkrando-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pokeparkrando"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.36.2", features = ["persistence"] }
pokeparkrando-core.workspace = true
rfd = "0.17.2"
semver = "1.0.28"
self_update = { version = "1.3.0", default-features = false, features = ["github", "rustls", "ureq"] }
thiserror.workspace = true

[lints]
workspace = true
