name: PR Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: python3 -mpip install poetry
      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Build distribution
        run: python3 -mPyInstaller pokeparkrando.spec
      - uses: actions/upload-artifact@v4
        with:
          name: PokéPark Randomizer Patcher
          path: dist